#!/usr/bin/env python3
"""Australia DKT (Driver Knowledge Test) practice data  -  public-domain-style.

The Australian DKT is administered by each state/territory (NSW, VIC, QLD,
SA, WA, TAS, ACT, NT) but the road rules are largely harmonised under the
Australian Road Rules. Questions below are grouped into the four practice
modes shown on the site:
  - full    : all questions in one mixed exam (auto-built by the generator)
  - signs   : Road Signs & Markings
  - rules   : Traffic Rules & Safety
  - alcohol : Alcohol & Drugs / Hazard Perception
Every question carries an explanation (the 'why'). Used by _gen_au.py to
build /au/.
"""
AU = {
    "name": "Australia (DKT) Practice Test",
    "source": "Australian Road Rules / state DKT syllabus (public domain style)",
    "categories": [
        {
            "id": "signs",
            "title": "Road Signs & Markings",
            "blurb": "Regulatory, warning and guide signs plus lane and edge markings.",
            "questions": [
                {"q": "What shape and colour is a STOP sign in Australia?",
                 "options": ["Red octagon with the word STOP", "Red triangle with GIVE WAY", "White rectangle with red border"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "A STOP sign is a red octagon  -  a unique shape so it can be recognised at night without reading it."},
                {"q": "A GIVE WAY sign in Australia is shaped like:",
                 "options": ["A red inverted triangle with white GIVE WAY", "A red octagon", "A yellow diamond"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Australia uses a red inverted triangle for give way; you must give way to all traffic on the continuing road."},
                {"q": "A red circle with a number inside (e.g. 60) means:",
                 "options": ["Maximum speed limit of 60 km/h", "Minimum speed of 60 km/h", "An advisory speed only"],
                 "answer": 0, "ref": "Speed signs",
                 "explanation": "A red-ringed circle is a maximum speed limit  -  you must not drive faster than the number shown."},
                {"q": "A red circle with a horizontal white bar means:",
                 "options": ["No entry", "Give way", "Stop"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "The red circle with a white horizontal bar is the 'no entry' sign  -  you must not enter that road."},
                {"q": "Warning signs in Australia are generally:",
                 "options": ["Diamond or rectangular, yellow-orange with a black symbol", "Red circles", "Blue squares"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "Warning signs are yellow-orange diamonds or rectangles with black symbols to alert you to hazards ahead."},
                {"q": "A yellow-orange diamond showing a railway track warns of:",
                 "options": ["A railway level crossing ahead", "Road works", "Pedestrians"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "The railway crossing warning sign means tracks cross the road ahead  -  slow down and be ready to stop."},
                {"q": "A zebra/striped pedestrian crossing warning sign means:",
                 "options": ["Pedestrians may be crossing  -  slow and give way", "No pedestrians allowed", "Bicycles only"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "This warning tells you a pedestrian crossing is ahead, so slow and be ready to give way."},
                {"q": "A 'children crossing' sign is used where:",
                 "options": ["Children cross under supervision during school hours", "Any road near a school at all times", "Only at night"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "The children crossing sign is placed where children cross with a supervisor (lollipop person); obey it when shown."},
                {"q": "Road work / construction signs are usually:",
                 "options": ["Orange diamonds or rectangles", "Blue squares", "White circles"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "Road work signs are orange to stand out; temporary speed limits shown with them are legally enforceable."},
                {"q": "A blue circular sign showing an arrow gives a:",
                 "options": ["Mandatory instruction (you must follow it)", "Warning only", "Advisory suggestion"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Blue circles give mandatory instructions, such as a required direction of travel."},
                {"q": "A white horizontal rectangle with route or place names is a:",
                 "options": ["Guide / information sign", "Regulatory sign", "Warning sign"],
                 "answer": 0, "ref": "Guide signs",
                 "explanation": "Guide signs are white (or green/blue) and give route, distance and place information."},
                {"q": "A yellow diamond with a curved vehicle on a slippery surface warns of:",
                 "options": ["A slippery road ahead", "The road narrowing", "A steep hill"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "The slippery road warning means reduce speed and avoid sudden braking or steering."},
                {"q": "A 'roundabout ahead' warning sign tells you to:",
                 "options": ["Slow down and prepare to give way", "Stop completely now", "Speed up to beat traffic"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "It warns a roundabout is coming; slow and be ready to give way to traffic already on it."},
                {"q": "A red-and-white 'road closed' barrier sign means:",
                 "options": ["The road is closed  -  do not enter", "Detour is optional", "School zone only"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Road closed signs mean you must not proceed; follow the signed detour."},
                {"q": "A 'T-intersection' warning sign means:",
                 "options": ["The road you are on ends  -  give way to the continuing road", "Merge to the left", "Roundabout ahead"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "At a T-intersection the driver on the terminating road gives way to traffic on the continuing road."},
                {"q": "Dashed white lane lines mean:",
                 "options": ["You may change lanes when it is safe", "You must never cross them", "They mark a bicycle-only lane"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "Dashed lines show you may change lanes when it is safe; solid lines restrict crossing."},
                {"q": "A solid white line at the edge of the road shows:",
                 "options": ["The road boundary / edge line", "A cycle lane", "A bus lane"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "The continuous edge line marks the boundary of the carriageway."},
                {"q": "Double centre lines where one is broken and one is solid on YOUR side mean:",
                 "options": ["You must not cross or straddle them", "You may cross freely", "Parking is allowed there"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "If the solid line is on your side you must not cross or straddle the lines."},
                {"q": "A thick white line across the road at an intersection is a:",
                 "options": ["Stop / give-way line", "A yellow speed line", "A parking bay"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "The transverse white line marks where you must stop or give way."},
                {"q": "A 'KEEP LEFT' sign with an arrow means:",
                 "options": ["Keep to the left of the line or island", "You may overtake on the right", "The road is one-way right"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Keep left signs tell you to stay to the left of a dividing line, island or obstruction."},
                {"q": "A red-light camera sign:",
                 "options": ["Warns that a camera enforces red lights", "Means it is only a speed camera", "Is decorative"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "It warns that running the red light is photographed and fined automatically."},
                {"q": "An arrow painted on the road surface showing a turn means:",
                 "options": ["The direction you are required to take", "Only a suggestion", "You must stop"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "Painted lane arrows show the required direction for that lane."},
                {"q": "A 'NO U-TURN' sign is shown as:",
                 "options": ["A red circle with a U-turn symbol crossed out", "A blue square", "A yellow diamond"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "A red circle banning the U-turn means you must not turn the vehicle to go back the way you came."},
                {"q": "A speed limit sign with a red circle and '40' means:",
                 "options": ["Maximum 40 km/h", "Minimum 40 km/h", "40 km/h only at night"],
                 "answer": 0, "ref": "Speed signs",
                 "explanation": "The red ring makes 40 a maximum speed limit for that stretch of road."},
                {"q": "A 'ONE WAY' sign tells you:",
                 "options": ["Traffic in that road flows only in the arrow's direction", "It is a two-way road", "No entry ahead"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "One-way signs mean you may only travel in the direction of the arrow."}
            ]
        },
        {
            "id": "rules",
            "title": "Traffic Rules & Safety",
            "blurb": "Give way, speed limits, roundabouts, seatbelts, mobile phones and safe driving.",
            "questions": [
                {"q": "What is the default speed limit in a built-up area unless signs say otherwise?",
                 "options": ["50 km/h", "60 km/h", "40 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "In built-up areas the default limit is 50 km/h unless a sign shows a different limit."},
                {"q": "What is the default speed limit outside built-up areas (open road) unless signed?",
                 "options": ["100 km/h", "110 km/h", "80 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "On open roads outside built-up areas the default limit is 100 km/h unless signed otherwise."},
                {"q": "Some freeways and rural highways have a limit of:",
                 "options": ["110 km/h", "130 km/h", "90 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "Many multi-lane freeways and some highways are signed at 110 km/h (state dependent)."},
                {"q": "In a school zone when the flashing lights are operating the limit is:",
                 "options": ["40 km/h", "50 km/h", "60 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "School zones drop to 40 km/h when the warning lights are flashing, to protect children."},
                {"q": "At a roundabout you must:",
                 "options": ["Give way to vehicles already on the roundabout", "Always have right of way", "Stop completely before entering"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "You must give way to any vehicle already on the roundabout, then signal and enter when safe."},
                {"q": "At a T-intersection, the driver on the terminating road must:",
                 "options": ["Give way to traffic on the continuing road", "Always go first", "Sound the horn"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "The vehicle on the road that ends gives way to traffic travelling along the continuing road."},
                {"q": "At an intersection with no signs or lines, you give way to:",
                 "options": ["The vehicle on your right", "The vehicle on your left", "The largest vehicle"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "With no controls, give way to the vehicle on your right (and to the right at a 4-way tie)."},
                {"q": "When turning right at an intersection you must give way to:",
                 "options": ["Oncoming vehicles going straight or turning left", "Only oncoming vehicles turning right", "No one"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "Oncoming traffic going straight or turning left has priority over your right turn."},
                {"q": "A fully licensed driver may use a mobile phone while driving if:",
                 "options": ["It is secured in a cradle and used hands-free", "They hold it briefly to check", "Only when stopped at a red light"],
                 "answer": 0, "ref": "Mobile phones",
                 "explanation": "Even fully licensed drivers may only use a phone that is fixed in a cradle and operated hands-free."},
                {"q": "Learner (L) and provisional (P1/P2) drivers must:",
                 "options": ["Not use a phone at all, even hands-free", "May use it hands-free", "May hold it at traffic lights"],
                 "answer": 0, "ref": "Mobile phones",
                 "explanation": "Learner and provisional drivers are banned from any phone use while driving, including hands-free."},
                {"q": "Seatbelts must be worn by:",
                 "options": ["All occupants of the vehicle", "The driver only", "Front-seat passengers only"],
                 "answer": 0, "ref": "Restraints",
                 "explanation": "Every occupant must wear a fitted seatbelt; the driver is responsible for child passengers being restrained."},
                {"q": "Children must travel in:",
                 "options": ["An approved child restraint or booster", "The front seat at any age", "Any available seat"],
                 "answer": 0, "ref": "Restraints",
                 "explanation": "Children must use an approved restraint suited to their size and age, often in the rear seat."},
                {"q": "When another vehicle is overtaking you, you should:",
                 "options": ["Keep left and not increase your speed", "Speed up to stay ahead", "Move to the right"],
                 "answer": 0, "ref": "Overtaking",
                 "explanation": "Do not speed up while being overtaken; keep left and let the overtaking driver pass safely."},
                {"q": "You may overtake on the left only when:",
                 "options": ["The vehicle ahead is turning right and it is safe", "At any time", "Never under any circumstance"],
                 "answer": 0, "ref": "Overtaking",
                 "explanation": "You may pass on the left only when the car ahead is signalling and turning right and there is room."},
                {"q": "In good conditions you should keep a following gap of at least:",
                 "options": ["2 to 3 seconds", "1 second", "Touching distance"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Use the 2 - 3 second rule; the gap gives you time to react and stop safely."},
                {"q": "In wet weather you should:",
                 "options": ["At least double your following distance", "Keep the same gap", "Halve your gap"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Wet roads increase stopping distance, so increase your gap to at least 4 seconds or more."},
                {"q": "You must not stop within how many metres of a pedestrian crossing?",
                 "options": ["20 metres", "5 metres", "50 metres"],
                 "answer": 0, "ref": "Parking",
                 "explanation": "Parking or stopping within 20 m of a crossing (and 10 m of an intersection without lights) is prohibited."},
                {"q": "Headlights must be switched on:",
                 "options": ["From 30 minutes after sunset to 30 minutes before sunrise", "Only on highways", "Never inside city limits"],
                 "answer": 0, "ref": "Lighting",
                 "explanation": "Use headlights between the half-hour after sunset and half-hour before sunrise, and in poor visibility."},
                {"q": "Fog lights should be used:",
                 "options": ["In fog or bad weather when visibility is low", "Every night", "Only in rain"],
                 "answer": 0, "ref": "Lighting",
                 "explanation": "Fog lights are for seriously reduced visibility; using them otherwise can dazzle others."},
                {"q": "When you hear an emergency vehicle siren you must:",
                 "options": ["Move left and let it pass", "Speed up to clear the way", "Ignore it"],
                 "answer": 0, "ref": "Emergency vehicles",
                 "explanation": "Pull over to the left and stop if necessary so the emergency vehicle can pass."},
                {"q": "At a railway level crossing with flashing lights you must:",
                 "options": ["Stop before the line and only proceed when safe", "Cross quickly before the train", "Reverse"],
                 "answer": 0, "ref": "Rail crossings",
                 "explanation": "Flashing lights mean a train is coming  -  stop before the line and do not proceed until safe."},
                {"q": "You must give way to a pedestrian who is:",
                 "options": ["On or waiting at a marked crossing", "Only on a footpath", "Standing on the kerb away from the road"],
                 "answer": 0, "ref": "Pedestrians",
                 "explanation": "Drivers must give way to pedestrians on or approaching a crossing."},
                {"q": "A yellow (amber) traffic light means you should:",
                 "options": ["Stop if you can do so safely before the line", "Accelerate to beat the red", "Ignore it"],
                 "answer": 0, "ref": "Traffic lights",
                 "explanation": "If you can stop safely, stop at a yellow light; only proceed if you are already too close to stop."},
                {"q": "When two lanes merge into one, the correct approach is:",
                 "options": ["Give way to the vehicle ahead and merge like a zip", "Force your way in", "Honk continuously"],
                 "answer": 0, "ref": "Merging",
                 "explanation": "In a merge, let the vehicle already ahead in the other lane go; merge smoothly (zipper merge)."},
                {"q": "You must carry your driver licence:",
                 "options": ["Whenever you are driving", "Only on long trips", "Never"],
                 "answer": 0, "ref": "Documents",
                 "explanation": "You must have your licence with you when driving and show it if police ask."}
            ]
        },
        {
            "id": "alcohol",
            "title": "Alcohol & Drugs / Hazard Perception",
            "blurb": "BAC limits, drug driving, fatigue, and spotting hazards early.",
            "questions": [
                {"q": "The legal blood alcohol concentration (BAC) limit for a fully licensed driver is:",
                 "options": ["0.05", "0.00", "0.08"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Most full licence holders must stay at or below 0.05 BAC."},
                {"q": "Learner (L) and provisional (P1/P2) drivers must have a BAC of:",
                 "options": ["0.00 (zero)", "0.05", "0.02"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Learner and provisional drivers must have no alcohol in their system  -  a zero limit applies."},
                {"q": "Drivers of buses, taxis and other commercial vehicles have a BAC limit of:",
                 "options": ["0.02", "0.05", "0.00"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Professional drivers must stay at or below 0.02 BAC."},
                {"q": "Driving with a BAC over the legal limit is:",
                 "options": ["A criminal offence with heavy penalties", "A minor issue", "Allowed if you feel fine"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Drink driving is a serious criminal offence carrying fines, licence loss and possible jail."},
                {"q": "Driving under the influence of illegal drugs (or some medicines) is:",
                 "options": ["Also illegal and can be tested roadside", "Allowed in small amounts", "Only illegal at night"],
                 "answer": 0, "ref": "Drug driving",
                 "explanation": "Drug driving is illegal; police can conduct roadside drug tests for common illicit drugs."},
                {"q": "If a medicine you take causes drowsiness you should:",
                 "options": ["Not drive until its effect has worn off", "Drive only on quiet roads", "Drive at night"],
                 "answer": 0, "ref": "Drug driving",
                 "explanation": "Any drug that makes you drowsy makes driving unsafe; do not drive until it has cleared."},
                {"q": "To manage fatigue on a long drive you should take a break at least every:",
                 "options": ["2 hours", "6 hours", "Rarely"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Stop for a break at least every two hours; a short walk or nap restores alertness."},
                {"q": "Signs that you are too tired to drive include:",
                 "options": ["Yawning, heavy eyes and missing exits", "Feeling extra alert", "Faster reactions"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Yawning, sore eyes and lapses in attention mean stop and rest immediately."},
                {"q": "If you feel drowsy while driving you should:",
                 "options": ["Pull over and rest", "Just open the window", "Accelerate to finish sooner"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Fresh air alone will not fix tiredness  -  stop in a safe place and rest."},
                {"q": "'Driver Reviver' sites are:",
                 "options": ["Rest stops with free coffee on busy holiday periods", "Speed camera locations", "Fuel-only bays"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Driver Reviver stops encourage a break with free coffee during peak holiday travel."},
                {"q": "Hazard perception means:",
                 "options": ["Spotting dangers early and reacting in time", "Only braking hard", "Ignoring the road"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "It is the skill of identifying hazards ahead and acting early to avoid a crash."},
                {"q": "Which of these is a hazard you should anticipate?",
                 "options": ["A child near the road, a parked car door, a wet patch", "Only another car", "A clear sunny day"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Hazards include anything that could make you slow, stop or steer  -  not just other vehicles."},
                {"q": "Good drivers constantly scan:",
                 "options": ["Ahead, mirrors and intersections", "Only the bonnet", "The radio dial"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Scanning ahead and checking mirrors helps you see hazards before they become emergencies."},
                {"q": "If a ball rolls onto the road ahead you should:",
                 "options": ["Slow down and be ready to stop", "Speed up to pass", "Ignore it"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "A child may run after the ball, so slow early and prepare to stop."},
                {"q": "In the wet, your stopping distance at 60 km/h is roughly:",
                 "options": ["Double the dry distance", "About the same", "About half"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Wet roads can double stopping distance, so increase your gap and slow down."},
                {"q": "Country and outback roads can have:",
                 "options": ["Kangaroos, livestock and wildlife", "Only city buses", "Tram tracks"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "Wildlife and stock are common on rural roads, especially at dawn and dusk."},
                {"q": "If you hit and injure livestock on a rural road you must:",
                 "options": ["Report it to the owner or police", "Drive on without stopping", "Do nothing"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "You must stop and report the incident to the owner or police as soon as possible."},
                {"q": "On country roads at night you should watch for:",
                 "options": ["Animal eyes / shadows on the road", "Only other cars", "Streetlights"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "Animals are hard to see at night; reduce speed and watch the edges of the road."},
                {"q": "Looking well ahead helps you:",
                 "options": ["Brake gently in time instead of slamming", "Drive faster", "Skip the mirrors"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Early scanning lets you brake smoothly, which is safer and more comfortable for passengers."},
                {"q": "When approaching the crest of a hill you should:",
                 "options": ["Slow down and keep left", "Accelerate", "Overtake immediately"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "You cannot see over a crest, so slow and keep left in case a hazard is on the other side."},
                {"q": "At 100 km/h a safe following gap is about:",
                 "options": ["3 seconds or more", "1 second", "Half a second"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Higher speeds need longer gaps; aim for at least 3 seconds and more in poor conditions."},
                {"q": "If the driver ahead brake-checks you, the safe response is to:",
                 "options": ["Keep a safe distance and not react aggressively", "Brake hard and tailgate", "Overtake sharply"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Stay calm, keep your distance and avoid escalating  -  your safety comes first."},
                {"q": "Cruise control on a long, steady open road is:",
                 "options": ["Fine when conditions are light and clear", "Always illegal", "Only for use in the city"],
                 "answer": 0, "ref": "Vehicle handling",
                 "explanation": "Cruise control is useful on steady roads but turn it off in heavy or changing traffic."},
                {"q": "Even 'a couple of drinks' can:",
                 "options": ["Impair judgement and push you over the limit", "Improve your driving", "Have no effect"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Small amounts of alcohol still affect judgement and can take you over 0.05."},
                {"q": "If you plan to drink, the safe choice is to:",
                 "options": ["Arrange a designated driver, taxi or rideshare", "Still drive home", "Drive faster to get home"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Plan ahead: never drive after drinking  -  use a sober driver or public transport."}
            ]
        }
    ]
}
