#!/usr/bin/env python3
"""Canada driver knowledge practice data — public-domain-style questions.
Canada is PROVINCE-BASED: each province runs its own test (Ontario G1/G2/G,
Quebec SAAQ, BC ICBC, Alberta Class 7, etc.). The questions below cover the
common national rules shared across provinces (signs, keep-right, speed in
km/h, winter driving, railways, wildlife, graduated licensing). Each question
carries an explanation (the 'why'). Used by _gen_ca.py to build /ca/.
"""
CA = {
    "name": "Canada (G1 / Class 7 Knowledge Test)",
    "source": "Provincial driver handbook syllabus (public domain style)",
    "questions": [
        # --- Licensing / graduated ---
        {"q": "In most provinces, a new driver starts with which licence class?",
         "options": ["A learner's permit (G1 / Class 7)", "A full licence", "A commercial licence"], "answer": 0,
         "ref": "Graduated licensing",
         "explanation": "Canada uses graduated licensing; you begin with a learner permit (G1 in Ontario, Class 7 in BC/Alberta) and progress in stages."},
        {"q": "As a G1 / Class 7 learner you must usually be accompanied by:",
         "options": ["A fully licensed driver with 4+ years experience", "Any friend", "No one needed"], "answer": 0,
         "ref": "Graduated licensing",
         "explanation": "Learners must drive with a qualified supervisor (e.g. 4+ years licensed) and often observe zero blood alcohol."},
        {"q": "New drivers in Canada typically face what alcohol limit?",
         "options": ["Zero (0.00%)", "0.08%", "0.05%"], "answer": 0,
         "ref": "Alcohol",
         "explanation": "Novice drivers are held to a zero tolerance (0.00% BAC) standard in most provinces."},
        {"q": "The federal criminal BAC limit for experienced drivers is:",
         "options": ["0.08%", "0.05%", "0.00%"], "answer": 0,
         "ref": "Alcohol",
         "explanation": "Over 0.08% BAC is a criminal offence nationwide, though many provinces suspend at 0.05%."},
        {"q": "How long is a G1 / Class 7 learner licence normally valid?",
         "options": ["About 1 year before the next stage", "Life", "3 months"], "answer": 0,
         "ref": "Graduated licensing",
         "explanation": "You usually hold the learner stage for about 12 months (sometimes less with driver training) before the road test."},

        # --- Keep right / position ---
        {"q": "In Canada you must generally drive:",
         "options": ["On the right-hand side of the road", "On the left", "In the middle"], "answer": 0,
         "ref": "Rules of the road",
         "explanation": "Canada drives on the right, the opposite of the UK; overtake on the left."},
        {"q": "On a multi-lane road you should normally use:",
         "options": ["The right lane and pass on the left", "The left lane always", "Any lane you like"], "answer": 0,
         "ref": "Lane discipline",
         "explanation": "Keep right and use the left lane only to pass, then move back."},
        {"q": "When two vehicles meet at an uncontrolled intersection, who goes first?",
         "options": ["The driver on the right", "The driver on the left", "Whoever is bigger"], "answer": 0,
         "ref": "Right of way",
         "explanation": "At an intersection with no signs, yield to the vehicle on your right."},
        {"q": "A 4-way stop sign means:",
         "options": ["First to stop goes first", "Left goes first", "Whoever is fastest"], "answer": 0,
         "ref": "Right of way",
         "explanation": "At a 4-way stop, the first vehicle to stop proceeds first; if tied, yield right."},
        {"q": "When turning left you must yield to:",
         "options": ["Oncoming traffic going straight", "Pedestrians only", "Nobody"], "answer": 0,
         "ref": "Right of way",
         "explanation": "A left turn crosses oncoming traffic, so wait for a safe gap in straight-ahead vehicles."},

        # --- Speed / limits (km/h) ---
        {"q": "Speed limits in Canada are posted in:",
         "options": ["km/h", "mph", "knots"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "Canada uses the metric system; limits such as 50 km/h in cities are shown in kilometres per hour."},
        {"q": "A typical city speed limit in Canada is:",
         "options": ["50 km/h", "30 mph", "80 km/h"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "Most urban areas set 50 km/h unless signed otherwise."},
        {"q": "On a rural highway without signs the limit is often:",
         "options": ["80 km/h", "50 km/h", "110 km/h"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "Many provinces default to 80 km/h on rural roads unless posted."},
        {"q": "School zones usually have a reduced limit of:",
         "options": ["30-40 km/h when children present", "70 km/h", "No special limit"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "School zones drop to about 30-40 km/h during posted times for child safety."},
        {"q": "You must always drive at a speed that is:",
         "options": ["Safe for the conditions", "The exact posted limit even in a storm", "As fast as traffic"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "The limit is a maximum; slow further for weather, light and traffic."},

        # --- Traffic signs ---
        {"q": "A red octagonal sign means:",
         "options": ["Stop", "Yield", "Speed limit"], "answer": 0,
         "ref": "Signs",
         "explanation": "The red octagon is the universal STOP sign; stop fully at the line."},
        {"q": "A red triangle sign with an exclamation means:",
         "options": ["Warning / hazard ahead", "Stop", "Parking"], "answer": 0,
         "ref": "Signs",
         "explanation": "Red triangles warn of hazards such as curves, hills or crossings."},
        {"q": "A circular red and white sign means:",
         "options": ["Do not enter / prohibition", "Yield", "Information"], "answer": 0,
         "ref": "Signs",
         "explanation": "Circular red-and-white signs are prohibitions, e.g. 'do not enter'."},
        {"q": "A green sign usually gives:",
         "options": ["Directions and information", "Warnings", "Stops"], "answer": 0,
         "ref": "Signs",
         "explanation": "Green signs guide drivers with route and destination information."},
        {"q": "A yellow pennant on the left warns of:",
         "options": ["A no-passing zone", "A school", "A railway"], "answer": 0,
         "ref": "Signs",
         "explanation": "The left-side yellow pennant marks where passing is not allowed."},
        {"q": "A pentagon sign (house shape) warns of:",
         "options": ["A school zone / crossing", "A hospital", "A curve"], "answer": 0,
         "ref": "Signs",
         "explanation": "The yellow pentagon indicates a school area and child pedestrians."},
        {"q": "A diamond sign warns of:",
         "options": ["A specific hazard (e.g. deer, bumps)", "A speed limit", "A stop"], "answer": 0,
         "ref": "Signs",
         "explanation": "Diamond shapes warn of road hazards such as wildlife, bumps or slippery sections."},
        {"q": "A flashing red light at an intersection means:",
         "options": ["Stop, then go when safe", "Slow down", "Ignore it"], "answer": 0,
         "ref": "Signals",
         "explanation": "A flashing red is treated like a stop sign: stop, yield, proceed when clear."},
        {"q": "A flashing green light (Quebec) means:",
         "options": ["Go, but pedestrians may be crossing / left turn permitted", "Stop", "Road closed"], "answer": 0,
         "ref": "Signals",
         "explanation": "In Quebec a flashing green allows you to turn left or go, watching for pedestrians."},

        # --- Winter driving (Canada-specific) ---
        {"q": "In winter you should increase your following distance because:",
         "options": ["Braking takes longer on ice/snow", "Cars are faster", "Laws require it"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Snow and ice lengthen stopping distance, so leave much more space."},
        {"q": "Winter tires are recommended or required in many provinces because:",
         "options": ["They grip better below 7°C", "They look nicer", "They are cheaper"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Rubber stays flexible in cold; some provinces mandate winter tires in season."},
        {"q": "If your car starts to skid on ice you should:",
         "options": ["Steer gently in the direction you want to go", "Brake hard", "Accelerate"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Ease off, look where you want to go and steer smoothly; avoid hard braking."},
        {"q": "Before a long winter trip you should:",
         "options": ["Carry a scraper, blanket and charged phone", "Nothing extra needed", "Remove the spare"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Winter kits (scraper, warmth, phone) help if you get stuck in cold."},
        {"q": "Black ice is dangerous because:",
         "options": ["It is nearly invisible", "It is blue", "It is warm"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Black ice is a thin clear glaze that looks like wet road; slow down on bridges and shaded spots."},
        {"q": "Using cruise control on snowy roads is:",
         "options": ["Not advised", "Required", "Faster"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Cruise control can cause sudden acceleration on slip; keep manual control."},
        {"q": "In heavy snow your headlights should be on:",
         "options": ["Always, for visibility", "Only at night", "Never"], "answer": 0,
         "ref": "Winter driving",
         "explanation": "Low light and whiteout reduce sight; use lights so others see you."},

        # --- Rail crossings ---
        {"q": "At a railway crossing with flashing lights you must:",
         "options": ["Stop and wait until lights stop", "Go if no train is visible", "Speed up"], "answer": 0,
         "ref": "Railways",
         "explanation": "Flashing lights mean a train is coming; stop well back and do not proceed until safe."},
        {"q": "You should never stop a vehicle:",
         "options": ["On a railway crossing", "At a red light", "In a parking spot"], "answer": 0,
         "ref": "Railways",
         "explanation": "Never stop on the tracks; a stalled car can be hit by a train."},
        {"q": "When a train is approaching you should:",
         "options": ["Stop at least 5 metres back", "Cross quickly", "Honk"], "answer": 0,
         "ref": "Railways",
         "explanation": "Stop well behind the crossing and only move once the train has fully passed."},
        {"q": "Trains are dangerous because they:",
         "options": ["Cannot stop quickly and are wider than the track", "Are slow", "Are small"], "answer": 0,
         "ref": "Railways",
         "explanation": "A train needs a long distance to stop and overhangs the rails; never race it."},

        # --- Wildlife / rural ---
        {"q": "In rural Canada a deer on the road means you should:",
         "options": ["Slow down and be ready to stop", "Speed up to pass", "Hoot constantly"], "answer": 0,
         "ref": "Wildlife",
         "explanation": "Deer (and moose) can dart out; brake smoothly and watch for more."},
        {"q": "If a large animal like a moose is on the road you should:",
         "options": ["Brake firmly and do not swerve hard", "Swerve into the ditch", "Accelerate"], "answer": 0,
         "ref": "Wildlife",
         "explanation": "Hitting a moose is severe; brake hard but avoid a violent swerve that could roll the car."},
        {"q": "At dusk and dawn in wooded areas you should:",
         "options": ["Be extra alert for animals", "Drive faster", "Close your eyes"], "answer": 0,
         "ref": "Wildlife",
         "explanation": "Animals are most active at low light; reduce speed near forests and water."},

        # --- Pedestrians / vulnerable ---
        {"q": "You must yield to pedestrians:",
         "options": ["At crosswalks and intersections", "Only on green lights", "Never"], "answer": 0,
         "ref": "Pedestrians",
         "explanation": "Pedestrians have priority at marked and unmarked crosswalks; stop and let them cross."},
        {"q": "When a school bus has its red lights flashing you must:",
         "options": ["Stop in both directions (except divided highways in some provinces)", "Pass slowly", "Honk"], "answer": 0,
         "ref": "School bus",
         "explanation": "Stop for a stopped school bus with flashing reds; children may be crossing. Rules vary slightly on divided roads."},
        {"q": "A pedestrian with a white cane is:",
         "options": ["Visually impaired; give way", "A worker", "A cyclist"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "A white cane signals blindness; stop and help them cross safely."},
        {"q": "When cycling you should:",
         "options": ["Follow the same rules as cars", "Ignore signs", "Ride against traffic"], "answer": 0,
         "ref": "Cyclists",
         "explanation": "Cyclists are vehicle operators; obey signs, signal and ride with traffic."},

        # --- Safety / documents ---
        {"q": "In Canada you must carry which documents when driving?",
         "options": ["Licence, insurance and registration", "Passport only", "Birth certificate"], "answer": 0,
         "ref": "Documents",
         "explanation": "Have your licence, proof of insurance and vehicle registration available if stopped."},
        {"q": "Seat belts are required for:",
         "options": ["The driver and all passengers", "Only the driver", "Nobody"], "answer": 0,
         "ref": "Safety",
         "explanation": "Every occupant must wear a seat belt; children need approved restraints."},
        {"q": "Using a handheld phone while driving is:",
         "options": ["Prohibited in every province", "Allowed", "Only banned at night"], "answer": 0,
         "ref": "Distraction",
         "explanation": "Handheld device use is banned nationwide; use hands-free only and minimize distraction."},
        {"q": "If you are in a collision you must:",
         "options": ["Stop, help and exchange information", "Drive away", "Hide"], "answer": 0,
         "ref": "Collisions",
         "explanation": "Stop, check for injuries, call 911 if needed and swap licence/insurance details."},
        {"q": "A child under a certain age/size must ride:",
         "options": ["In an approved child car seat", "In the front seat", "Unrestrained"], "answer": 0,
         "ref": "Child safety",
         "explanation": "Young children need the correct car seat or booster per provincial law."},
        {"q": "When parked on a hill you should:",
         "options": ["Turn wheels to the curb and set the brake", "Leave it in gear only", "Point downhill"], "answer": 0,
         "ref": "Parking",
         "explanation": "Curb your wheels so the car rolls into the curb, not the road, if it moves."},

        # --- General handling ---
        {"q": "When being passed you should:",
         "options": ["Keep speed and stay right", "Speed up", "Move left"], "answer": 0,
         "ref": "Overtaking",
         "explanation": "Don't accelerate; hold steady and let the passer complete safely."},
        {"q": "You may pass another car on the right only when:",
         "options": ["The other car is turning left and road is clear", "Always on highways", "Never"], "answer": 0,
         "ref": "Overtaking",
         "explanation": "Passing on the right is allowed only in specific safe situations, e.g. a left-turning vehicle."},
        {"q": "A solid line on your side means:",
         "options": ["Do not pass", "Pass freely", "Bus lane"], "answer": 0,
         "ref": "Road markings",
         "explanation": "A solid centre line on your side prohibits crossing to overtake."},
        {"q": "At a yellow (amber) light you should:",
         "options": ["Stop if you can do so safely", "Speed up to beat it", "Always go"], "answer": 0,
         "ref": "Signals",
         "explanation": "Amber means stop if safe; only continue if too close to stop."},
        {"q": "Headlights must be on from:",
         "options": ["30 min after sunset to 30 min before sunrise", "Noon only", "Never"], "answer": 0,
         "ref": "Lighting",
         "explanation": "Use headlights from dusk to dawn and in poor visibility."},
        {"q": "When towing you should:",
         "options": ["Stay within the speed and weight limits", "Exceed limits", "Not signal"], "answer": 0,
         "ref": "Towing",
         "explanation": "Trailers add length and weight; obey lower limits and check connections."},
        {"q": "A roundabout is entered by:",
         "options": ["Yielding to traffic already in it (circulating counterclockwise)", "Barging in", "Stopping in the middle"], "answer": 0,
         "ref": "Roundabouts",
         "explanation": "Canadian roundabouts go counterclockwise; yield to cars already circling, then enter."},
        {"q": "If your brakes fail you should:",
         "options": ["Pump the brake, use the parking brake, downshift", "Close your eyes", "Floor the gas"], "answer": 0,
         "ref": "Emergencies",
         "explanation": "Try pumping, engage the parking brake gradually and shift down to slow safely."},
        {"q": "Visibility is low in fog. You should:",
         "options": ["Slow down and use low beams", "Use high beams", "Speed up"], "answer": 0,
         "ref": "Visibility",
         "explanation": "Low beams reduce glare in fog; high beams reflect back and worsen sight."},
        {"q": "You see a construction zone. You should:",
         "options": ["Slow to the posted temporary limit", "Keep full speed", "Change lanes sharply"], "answer": 0,
         "ref": "Work zones",
         "explanation": "Temporary limits in work zones are enforced and protect workers."},
        {"q": "Sharing the road with a large truck you should:",
         "options": ["Give extra room and avoid blind spots", "Cut in front closely", "Tailgate"], "answer": 0,
         "ref": "Large vehicles",
         "explanation": "Trucks have big blind spots and long stopping distances; don't linger beside them."},
        {"q": "When parallel parking you should:",
         "options": ["Signal, position, and reverse in smoothly", "Jump in fast", "Not signal"], "answer": 0,
         "ref": "Parking",
         "explanation": "Signal, line up, and back into the space with care and observation."}
    ]
}
