#!/usr/bin/env python3
"""Germany Fahrschule Theoriepruefung practice data - bilingual (DE/EN).

The German theory test (Theoriepruefung) is run by the TUEV / DEKRA and based
on the German road traffic regulations (StVO). Germany drives on the RIGHT.
This file is BILINGUAL: every question carries both a German (de) and an
English (en) version of the question, options and explanation, so the page
can switch language on the fly. Questions are grouped into:
  - full     : all questions mixed (auto-built by generator)
  - signs    : Verkehrszeichen (Traffic Signs)
  - rules    : Verkehrsregeln (Driving Rules)
  - safety   : Verkehrssicherheit (Road Safety)
Used by _gen_de.py to build /de/.
"""
DE = {
    "name": "Germany (Fahrschule Theoriepruefung)",
    "source": "German StVO / TUEV-DEKRA theory syllabus (public domain style)",
    "categories": [
        {
            "id": "signs",
            "title_de": "Verkehrszeichen",
            "title_en": "Traffic Signs",
            "blurb_de": "Gefahrzeichen, Vorschriftszeichen und Verkehrseinrichtungen.",
            "blurb_en": "Warning signs, regulatory signs and road markings.",
            "questions": [
                {"q_de":"Wie ist ein STOP-Schild in Deutschland gestaltet?",
                 "q_en":"What shape and colour is a STOP sign in Germany?",
                 "options_de":["Achteckig, rot mit weissem 'STOP'","Dreieckig, rot mit Ausrufezeichen","Rund, blau mit Pfeil"],
                 "options_en":["Red octagon with the word STOP","Red triangle with an exclamation mark","Blue circle with an arrow"],
                 "answer":0,"e_de":"Das STOP-Schild ist ein rotes Achteck - eine eigene Form, damit es auch nachts erkannt wird.","e_en":"A STOP sign is a red octagon - a unique shape so it is recognised at night."},
                {"q_de":"Welches Schild zeigt eine Vorfahrtstrasse an?",
                 "q_en":"Which sign marks a priority road?",
                 "options_de":["Gelbes Quadrat mit weissem Pfeil","Rotes Achteck","Blaues Rechteck"],
                 "options_en":["Yellow square with a white arrow","Red octagon","Blue rectangle"],
                 "answer":0,"e_de":"Das gelbe quadratische Schild 'Vorfahrt' zeigt an, dass Sie auf dieser Strasse Vorfahrt haben.","e_en":"The yellow square 'priority road' sign means you have right of way along that road."},
                {"q_de":"Was bedeutet ein rundes Schild mit rotem Rand und einer Zahl (z. B. 50)?",
                 "q_en":"What does a round sign with a red ring and a number (e.g. 50) mean?",
                 "options_de":["Hoechstgeschwindigkeit 50 km/h","Mindestgeschwindigkeit 50 km/h","Nur ein Hinweis"],
                 "options_en":["Maximum speed of 50 km/h","Minimum speed of 50 km/h","Only an advisory"],
                 "answer":0,"e_de":"Ein rot umrandetes rundes Schild ist ein Hoechstgeschwindigkeitsgebot - schneller fahren ist verboten.","e_en":"A red-ringed circle is a maximum speed limit - exceeding it is forbidden."},
                {"q_de":"Was bedeutet ein rundes Schild mit rotem Rand und weissem Querbalken?",
                 "q_en":"What does a round sign with a red ring and a white horizontal bar mean?",
                 "options_de":["Einfahrt verboten","Vorfahrt gewaehren","Halt"],
                 "options_en":["No entry","Give way","Stop"],
                 "answer":0,"e_de":"Das Schild 'Verbot der Einfahrt' (rote Kreisscheibe mit weissem Balken) verbietet das Befahren der Strasse.","e_en":"The 'no entry' sign (red disc with a white bar) forbids entering that road."},
                {"q_de":"Wie sehen Gefahrenzeichen in Deutschland meistens aus?",
                 "q_en":"What do warning signs in Germany usually look like?",
                 "options_de":["Dreieck mit rotem Rand und gelb-orangem Feld","Rotes Achteck","Blaues Rechteck"],
                 "options_en":["Triangle with red border and yellow-orange field","Red octagon","Blue rectangle"],
                 "answer":0,"e_de":"Gefahrenzeichen sind rote Dreiecke mit gelb-orangem Innenteil und schwarzer Symbolik.","e_en":"Warning signs are red-bordered triangles with a yellow-orange field and black symbol."},
                {"q_de":"Was bedeutet ein blaues rundes Schild?",
                 "q_en":"What does a blue circular sign mean?",
                 "options_de":["Ein Gebot (z. B. vorgeschriebene Fahrtrichtung)","Eine Warnung","Ein Tempolimit"],
                 "options_en":["A mandatory instruction (e.g. required direction)","A warning","A speed limit"],
                 "answer":0,"e_de":"Blaue Rundzeichen sind Gebotszeichen - Sie MUESSEN das Gezeigte tun.","e_en":"Blue circles are mandatory signs - you must follow what they show."},
                {"q_de":"Was warnt ein gelb-rotes Baustellenzeichen?",
                 "q_en":"What does an orange-red road works sign warn of?",
                 "options_de":["Arbeiten an der Strasse","Eine Schule","Einen Bahnuebergang"],
                 "options_en":["Road works ahead","A school","A railway crossing"],
                 "answer":0,"e_de":"Baustellenzeichen sind gelb-orange; dort geltende Tempolimits sind verbindlich.","e_en":"Road works signs are orange; temporary speed limits shown with them are legally enforceable."},
                {"q_de":"Was bedeutet ein dreieckiges Schild mit Fussgaengersymbol?",
                 "q_en":"What does a triangular sign with a pedestrian symbol mean?",
                 "options_de":["Fussgaenger moeglich - langsam fahren und Vorfahrt gewaehren","Keine Fussgaenger","Nur Radfahrer"],
                 "options_en":["Pedestrians possible - slow and give way","No pedestrians","Cyclists only"],
                 "answer":0,"e_de":"Es warnt vor Fussgaengern; Sie muessen notfalls anhalten und Vorfahrt gewaehren.","e_en":"It warns of pedestrians; slow down and be ready to give way."},
                {"q_de":"Was warnt ein dreieckiges Schild mit spielenden Kindern?",
                 "q_en":"What does a triangular sign with playing children warn of?",
                 "options_de":["Eine Schule oder Stelle mit spielenden Kindern","Nur einen Spielplatz","Eine Bushaltestelle"],
                 "options_en":["A school or place where children may play","Only a playground","A bus stop"],
                 "answer":0,"e_de":"Es markiert Bereiche mit Kindern, die unvorhersehbar auf die Strasse laufen koennen.","e_en":"It marks areas with children who may unexpectedly run onto the road."},
                {"q_de":"Was bedeutet ein dreieckiges Schild mit einem gleichseitigen Kreuz (Bahn)?",
                 "q_en":"What does a triangular sign with a cross (railway) mean?",
                 "options_de":["Eine Bahnueberquerung ohne Schranke","Eine Baustelle","Eine Kurve"],
                 "options_en":["A level crossing without barriers","Road works","A bend"],
                 "answer":0,"e_de":"Es warnt vor einem Bahnuebergang; vor allem bei fehlenden Schranken besonders vorsichtig sein.","e_en":"It warns of a railway level crossing; be especially careful where there are no barriers."},
                {"q_de":"Was warnt ein Schild mit rutschendem Auto auf glatter Strasse?",
                 "q_en":"What does a sign showing a car skidding on a slippery road warn of?",
                 "options_de":["Glatte Fahrbahn - Geschwindigkeit anpassen","Strasse verengt sich","Steile Steigung"],
                 "options_en":["Slippery road - reduce speed","Road narrows","Steep hill"],
                 "answer":0,"e_de":"Bei Nasse, Schnee oder Eis bremst das Fahrzeug viel laenger.","e_en":"On wet, snowy or icy roads the car takes much longer to stop."},
                {"q_de":"Was bedeutet ein Warnzeichen mit Kreisverkehr?",
                 "q_en":"What does a warning sign for a roundabout mean?",
                 "options_de":["Kreisverkehr voraus - langsamer fahren","Sofort anhalten","Beschleunigen"],
                 "options_en":["Roundabout ahead - slow down","Stop completely","Speed up"],
                 "answer":0,"e_de":"Es kündigt einen Kreisverkehr an; Sie muessen Vorfahrt gewaehren.","e_en":"It warns of a roundabout; you must give way to traffic already on it."},
                {"q_de":"Wie ist ein 'Vorfahrt gewaehren'-Schild gestaltet?",
                 "q_en":"What does a 'give way' sign look like in Germany?",
                 "options_de":["Weisses Dreieck mit rotem Rand","Rotes Achteck","Blaues Rechteck"],
                 "options_en":["White triangle with red border","Red octagon","Blue rectangle"],
                 "answer":0,"e_de":"Das weisse Dreieck mit rotem Rand heisst 'Vorfahrt gewaehren'.","e_en":"The white triangle with a red border means 'give way'."},
                {"q_de":"Was bedeutet ein Schild 'Verbot des Ueberholens'?",
                 "q_en":"What does a 'no overtaking' sign mean?",
                 "options_de":["Das Ueberholen des Vorausfahrenden ist verboten","Ein Tempolimit","Ein Radfahrergebot"],
                 "options_en":["Overtaking the vehicle ahead is forbidden","A speed limit","A cycle instruction"],
                 "answer":0,"e_de":"Das rote Rundzeichen mit zwei Fahrzeugen verbietet das Ueberholen, bis das Verbot endet.","e_en":"The red circle with two vehicles bans overtaking until the restriction ends."},
                {"q_de":"Was bedeutet ein Schild 'Verbot der Umkehr' (Wendeverbot)?",
                 "q_en":"What does a 'no U-turn' sign mean?",
                 "options_de":["Das Wenden ist verboten","Nur eine Richtung erlaubt","Kein Halt"],
                 "options_en":["Turning back is forbidden","One-way only","No stopping"],
                 "answer":0,"e_de":"Ein rotes Rundzeichen mit U-Pfeil verbietet das Wenden.","e_en":"A red circle with a U-turn symbol bans turning back."},
                {"q_de":"Was zeigt ein blaues Rundzeichen mit Pfeil?",
                 "q_en":"What does a blue circular sign with an arrow show?",
                 "options_de":["Eine vorgeschriebene Fahrtrichtung","Nur eine Warnung","Eine Empfehlung"],
                 "options_en":["A required direction of travel","Only a warning","A suggestion"],
                 "answer":0,"e_de":"Blaue Gebotszeichen schreiben eine bestimmte Fahrtrichtung vor.","e_en":"Blue mandatory signs prescribe a specific direction of travel."},
                {"q_de":"Was bedeutet ein Autobahn-Schild?",
                 "q_en":"What does a motorway (Autobahn) sign look like?",
                 "options_de":["Blaues Rechteck mit weisser 'A' und Nummer","Gelbes Rechteck","Rotes Dreieck"],
                 "options_en":["Blue rectangle with white 'A' and number","Yellow rectangle","Red triangle"],
                 "answer":0,"e_de":"Autobahnen sind mit blauen Schildern und einem weissen 'A' gekennzeichnet.","e_en":"Motorways are signed in blue with a white 'A' and route number."},
                {"q_de":"Was warnt ein Schild mit zusammenlaufenden Pfeilen?",
                 "q_en":"What does a sign with converging arrows warn of?",
                 "options_de":["Fahrbahnverengung - rechtzeitig einordnen","Eine Baustelle","Einen Bahnuebergang"],
                 "options_en":["Road narrowing - merge in good time","Road works","A railway crossing"],
                 "answer":0,"e_de":"Die Spur wird schmaler; fahren Sie vorausschauend und rueckhaltend.","e_en":"The lane narrows; merge early and yield."},
                {"q_de":"Was bedeutet ein Schild 'Wildwechsel'?",
                 "q_en":"What does a 'wild animals crossing' sign mean?",
                 "options_de":["Tiere koennen auf die Strasse springen","Nur Haustiere","Eine Zoo-Ausfahrt"],
                 "options_en":["Animals may dash onto the road","Only pets","A zoo exit"],
                 "answer":0,"e_de":"In laendlichen Gebieten (v. a. bei Daemmerung) mit Wild rechnen und langsamer fahren.","e_en":"In rural areas, especially at dusk, expect wildlife and slow down."},
                {"q_de":"Was bedeutet ein blaues Rechteck mit Ortsnamen?",
                 "q_en":"What does a blue rectangle with a place name mean?",
                 "options_de":["Ein Hinweis- oder Orientierungsschild","Ein Verbotsschild","Ein Warnschild"],
                 "options_en":["An information or orientation sign","A prohibition sign","A warning sign"],
                 "answer":0,"e_de":"Blaue (oder gruene) Schilder geben Auskunft ueber Orte und Strecken.","e_en":"Blue or green signs give place and route information."},
                {"q_de":"Was bedeutet ein gruenes Schild mit weissem Fahrrad?",
                 "q_en":"What does a green sign with a white bicycle mean?",
                 "options_de":["Ein Radweg (benutzungspflichtig)","Nur Fussgaenger","Eine Baustelle"],
                 "options_en":["A compulsory cycle path","Pedestrians only","Road works"],
                 "answer":0,"e_de":"Blaue/gruene Schilder mit Radsymbol zeigen oft benutzungspflichtige Radwege.","e_en":"Blue/green signs with a bike symbol often mark mandatory cycle paths."},
                {"q_de":"Was bedeutet ein gelbes Schild 'Umweltzone'?",
                 "q_en":"What does a yellow 'environmental zone' sign mean?",
                 "options_de":["Nur mit gueltiger Feinstaubplakette befahren","Kostenlose Parkzone","Eine Schule"],
                 "options_en":["Only with a valid emissions sticker","Free parking zone","A school"],
                 "answer":0,"e_de":"In Umweltzonen ist eine gruene Plakette (Feinstaubplakette) Pflicht.","e_en":"In environmental zones a green emissions sticker is mandatory."},
                {"q_de":"Was zeigt eine rote Ampel?",
                 "q_en":"What does a red traffic light mean?",
                 "options_de":["Anhalten vor der Haltelinie","Weiterfahren wenn frei","Nur langsamer werden"],
                 "options_en":["Stop before the stop line","Proceed if clear","Only slow down"],
                 "answer":0,"e_de":"Rot bedeutet Halt. Warten Sie hinter der Haltelinie, bis es gruen wird.","e_en":"Red means stop. Wait behind the line until the light is green."},
                {"q_de":"Eine duenne gelbe Linie auf der Fahrbahn bedeutet in Deutschland meist:",
                 "q_en":"A thin yellow line on the road in Germany usually means:",
                 "options_de":["Eine Baustellen- oder Temporaermarkierung","Die Strassenbegrenzung","Radfahrstreifen"],
                 "options_en":["A road works or temporary marking","The road edge","A cycle lane"],
                 "answer":0,"e_de":"Gelbe Markierungen sind in Deutschland selten und meist temporaer (Baustelle).","e_en":"Yellow markings are rare in Germany and usually temporary (road works)."}
            ]
        },
        {
            "id": "rules",
            "title_de": "Verkehrsregeln",
            "title_en": "Driving Rules",
            "blurb_de": "Tempolimits, Vorfahrt, Ueberholen, Alkohol und Pflichten.",
            "blurb_en": "Speed limits, right of way, overtaking, alcohol and obligations.",
            "questions": [
                {"q_de":"Wie hoch ist die Hoechstgeschwindigkeit innerorts (ohne Zeichen)?",
                 "q_en":"What is the default speed limit in a built-up area (no sign)?",
                 "options_de":["50 km/h","30 km/h","70 km/h"],
                 "options_en":["50 km/h","30 km/h","70 km/h"],
                 "answer":0,"e_de":"Innerorts gilt ohne Zeichen Tempo 50.","e_en":"In built-up areas the default limit is 50 km/h unless signed."},
                {"q_de":"Wie hoch ist die empfohlene Hoechstgeschwindigkeit ausserorts (Landstrasse)?",
                 "q_en":"What is the recommended speed limit outside towns (country road)?",
                 "options_de":["100 km/h","80 km/h","130 km/h"],
                 "options_en":["100 km/h","80 km/h","130 km/h"],
                 "answer":0,"e_de":"Ausserorts ohne Zeichen gilt Tempo 100 (Richtwert).","e_en":"Outside towns the default is 100 km/h (advisory) unless signed."},
                {"q_de":"Gibt es auf der Autobahn immer ein Tempolimit?",
                 "q_en":"Is there always a speed limit on the motorway?",
                 "options_de":["Nein, oft kein Limit, aber Richtwert 130 km/h","Immer 120 km/h","Immer 100 km/h"],
                 "options_en":["No, often no limit but 130 km/h advisory","Always 120 km/h","Always 100 km/h"],
                 "answer":0,"e_de":"Viele Autobahnabschnitte sind limitfrei; 130 km/h ist ein Richtwert, kein Zwang.","e_en":"Many Autobahn sections have no limit; 130 km/h is an advisory, not mandatory."},
                {"q_de":"Wer hat an einer unbeschilderten Kreuzung Vorfahrt?",
                 "q_en":"Who has priority at an unmarked junction?",
                 "options_de":["Der Verkehr von rechts ('rechts vor links')","Der Verkehr von links","Wer schneller ist"],
                 "options_en":["Traffic from the right ('right before left')","Traffic from the left","Whoever is faster"],
                 "answer":0,"e_de":"Ohne Vorfahrtszeichen gilt 'rechts vor links'.","e_en":"With no signs, 'right before left' applies."},
                {"q_de":"Wer hat in einem Kreisverkehr Vorfahrt?",
                 "q_en":"Who has priority in a roundabout?",
                 "options_de":["Der Verkehr im Kreis","Der Einfahrende","Immer wer hupt"],
                 "options_en":["Traffic already in the roundabout","The entering driver","Whoever honks"],
                 "answer":0,"e_de":"Im Kreisverkehr hat der Innverkehr Vorfahrt; Sie mussen gewaehren.","e_en":"Traffic in the roundabout has priority; you must give way."},
                {"q_de":"Muss ein Sicherheitsgurt angelegt sein?",
                 "q_en":"Must a seatbelt be worn?",
                 "options_de":["Ja, von allen Insassen","Nur vom Fahrer","Nur auf der Autobahn"],
                 "options_en":["Yes, by all occupants","Driver only","Only on the motorway"],
                 "answer":0,"e_de":"Gurte sind fuer alle Insassen Pflicht; der Fahrer haftet fuer Kinder.","e_en":"Seatbelts are mandatory for all occupants; the driver is responsible for children."},
                {"q_de":"Darf man waehrend der Fahrt ein Handy in der Hand halten?",
                 "q_en":"May you hold a phone in your hand while driving?",
                 "options_de":["Nein, das ist verboten (Freisprechen erlaubt)","Ja, kurz zum Schauen","Nur an der Ampel"],
                 "options_en":["No, it is banned (hands-free is allowed)","Yes, briefly to look","Only at traffic lights"],
                 "answer":0,"e_de":"Das Halten und Bedienen des Handys beim Fahren ist verboten; Freisprechen ist erlaubt.","e_en":"Holding and using a hand-held phone while driving is banned; hands-free is allowed."},
                {"q_de":"Wie hoch ist die allgemeine Alkoholgrenze (Blut)?",
                 "q_en":"What is the general blood alcohol limit?",
                 "options_de":["0,5 Promille (0,05)","0,0 Promille","0,8 Promille"],
                 "options_en":["0.05 (0.5 per mille)","0.00","0.08"],
                 "answer":0,"e_de":"Fuer volljaehrige Fahrer gilt 0,5 Promille; darueber ist es eine Straftat.","e_en":"For adult drivers the limit is 0.05; above it is a criminal offence."},
                {"q_de":"Welche Grenze gilt fuer Fahranfaenger (unter 21 / unter 2 Jahren)?",
                 "q_en":"What limit applies to novice drivers (under 21 / under 2 years)?",
                 "options_de":["0,0 Promille (absolutes Alkoholverbot)","0,5 Promille","0,3 Promille"],
                 "options_en":["0.00 (absolute alcohol ban)","0.05","0.03"],
                 "answer":0,"e_de":"Anfaenger unter 21 bzw. unter 2 Jahren muessen 0,0 Promille haben.","e_en":"Drivers under 21 or within 2 years must have zero alcohol."},
                {"q_de":"Wie lang ist der Bremsweg bei 100 km/h etwa?",
                 "q_en":"What is the braking distance at about 100 km/h?",
                 "options_de":["Etwa 50 Meter (Reaktion + Bremsen)","Etwa 10 Meter","Etwa 5 Meter"],
                 "options_en":["About 50 metres (reaction + braking)","About 10 metres","About 5 metres"],
                 "answer":0,"e_de":"Bei 100 km/h braucht ein Auto zum Anhalten rund 50 m.","e_en":"At 100 km/h a car needs about 50 m to stop."},
                {"q_de":"Welchen Mindestabstand sollten Sie halten?",
                 "options_de":["Mindestens 2 Sekunden (Abstandsregel)","1 Sekunde","Tuchfuehlung"],
                 "options_en":["At least 2 seconds (distance rule)","1 second","Touching distance"],
                 "q_en":"What minimum following distance should you keep?",
                 "answer":0,"e_de":"Die 2-Sekunden-Regel gibt Zeit zum Reagieren.","e_en":"The 2-second rule gives time to react."},
                {"q_de":"Wo wird in Deutschland ueberholt?",
                 "q_en":"On which side is overtaking done in Germany?",
                 "options_de":["Links","Rechts","Ueberall"],
                 "options_en":["On the left","On the right","Anywhere"],
                 "answer":0,"e_de":"Da rechts gefahren wird, wird links ueberholt.","e_en":"Since driving is on the right, overtaking is on the left."},
                {"q_de":"Wenn Sie ueberholt werden, sollten Sie:",
                 "q_en":"When you are being overtaken, you should:",
                 "options_de":["Nach rechts halten und nicht beschleunigen","Beschleunigen","Nach links ziehen"],
                 "options_en":["Keep right and not speed up","Speed up","Move left"],
                 "answer":0,"e_de":"Bleiben Sie rechts und bremsen Sie notfalls sanft.","e_en":"Stay right and brake gently if needed."},
                {"q_de":"An einer Kreuzung mussen Sie wartende Fussgaenger:",
                 "q_en":"At a crossing you must let waiting pedestrians:",
                 "options_de":["Durchlassen (Vorfahrt gewaehren)","Schnell ueberholen","Ignorieren"],
                 "options_en":["Cross (give way to them)","Hurry past","Ignore"],
                 "answer":0,"e_de":"Fussgaengern auf oder an der Furt muss Vorrang gewaehrt werden.","e_en":"Pedestrians on or at a crossing must be given priority."},
                {"q_de":"Was ist die 'Rettungsgasse' auf der Autobahn?",
                 "q_en":"What is the 'emergency lane' (Rettungsgasse) on the motorway?",
                 "options_de":["Bei Stau den rechten Zwischenraum freimachen","Immer ganz rechts fahren","Nie anhalten"],
                 "options_en":["Clear the gap to the right when jammed","Always drive far right","Never stop"],
                 "answer":0,"e_de":"Bei Stau wird rechts (bzw. zwischen den zwei linken Spuren) Platz fuer Rettungsfahrzeuge gelassen.","e_en":"When jammed, a lane is kept clear on the right for emergency vehicles."},
                {"q_de":"Wann sind Winterreifen Pflicht?",
                 "q_en":"When are winter tyres mandatory?",
                 "options_de":["Bei winterlichen Strassenbedingungen (Schnee, Eis)","Nur von Oktober bis Ostern","Immer"],
                 "options_en":["In winter road conditions (snow, ice)","Only Oct to Easter","Always"],
                 "answer":0,"e_de":"Bei Schnee, Schneematsch oder Eis muessen Winterreifen aufgezogen sein.","e_en":"In snow, slush or ice, winter tyres are required."},
                {"q_de":"In einer Umweltzone benoetigen Sie:",
                 "q_en":"In an environmental zone you need:",
                 "options_de":["Eine gruene Feinstaubplakette","Kein Kennzeichen","Eine gelbe Plakette"],
                 "options_en":["A green emissions sticker","No badge","A yellow badge"],
                 "answer":0,"e_de":"Nur Fahrzeuge mit gruener Plakette duerfen Umweltzonen befahren.","e_en":"Only vehicles with a green sticker may enter environmental zones."},
                {"q_de":"Auf einer Vorfahrtstrasse haben Sie:",
                 "q_en":"On a priority road you have:",
                 "options_de":["Vorfahrt vor einmuendenden Strassen","Immer anhalten","Keine Vorfahrt"],
                 "options_en":["Priority over crossing roads","Always stop","No priority"],
                 "answer":0,"e_de":"Auf der Vorfahrtstrasse haben Sie Vorrang vor dem Querverkehr.","e_en":"On the priority road you have right of way over crossing traffic."},
                {"q_de":"Kinder muessen in einem geeigneten:",
                 "q_en":"Children must use a suitable:",
                 "options_de":["Kindersitz / Ruecksitz (alterabhaengig)","Vordersitz ab 3 Jahren","Keinem Sitz"],
                 "options_en":["Child seat / rear seat (age-based)","Front seat from age 3","No seat"],
                 "answer":0,"e_de":"Kinder brauchen einen altersgerechten Kindersitz, meist hinten.","e_en":"Children need an age-appropriate child seat, usually in the rear."},
                {"q_de":"Welche Dokumente muessen Sie mitfuehren?",
                 "q_en":"Which documents must you carry?",
                 "options_de":["Fuehrerschein, Fahrzeugschein, Versicherung","Nur den Fuehrerschein","Nichts"],
                 "options_en":["Licence, registration, insurance","Licence only","Nothing"],
                 "answer":0,"e_de":"Mitzufuehren sind Fuehrerschein, Fahrzeugschein und Versicherungsnachweis.","e_en":"Carry your licence, vehicle registration and proof of insurance."},
                {"q_de":"Wo darf nicht geparkt werden?",
                 "q_en":"Where is parking forbidden?",
                 "options_de":["Innerhalb von 5 m vor Kreuzungen/Einmündungen","An jeder Strasse","Nur auf der Autobahn"],
                 "options_en":["Within 5 m of junctions","On any street","Only on the motorway"],
                 "answer":0,"e_de":"Das Parken vor Kreuzungen/Einmündungen behindert die Sicht und ist verboten.","e_en":"Parking near junctions blocks sight lines and is forbidden."},
                {"q_de":"Bei Nebel sind Nebelschlussleuchten erst ab:",
                 "q_en":"In fog, rear fog lights are only used from:",
                 "options_de":["Sichtweite unter 50 m","Immer","Nie"],
                 "options_en":["Visibility under 50 m","Always","Never"],
                 "answer":0,"e_de":"Nebelschlussleuchten blenden sonst - nur bei Sicht unter 50 m.","e_en":"Rear fog lights dazzle otherwise - only use them under 50 m visibility."},
                {"q_de":"Wer muss Vorfahrt gewaehren, wenn Sie auf der Vorfahrtstrasse fahren?",
                 "q_en":"Who must give way when you are on the priority road?",
                 "options_de":["Der Querverkehr","Sie selbst","Niemand muss","Der Fussgaenger"],
                 "options_en":["Crossing traffic","You yourself","No one has to","The pedestrian"],
                 "answer":0,"e_de":"Der Querverkehr muss Ihnen Vorfahrt gewaehren.","e_en":"Crossing traffic must give way to you."}
            ]
        },
        {
            "id": "safety",
            "title_de": "Verkehrssicherheit",
            "title_en": "Road Safety",
            "blurb_de": "Muedigkeit, Gefahrenwahrnehmung, Wetter und Erste Hilfe.",
            "blurb_en": "Fatigue, hazard perception, weather and first aid.",
            "questions": [
                {"q_de":"Wie oft sollten Sie bei laengeren Fahrten Pause machen?",
                 "q_en":"How often should you take a break on long drives?",
                 "options_de":["Alle 2 Stunden fuer ~15 Minuten","Alle 6 Stunden","Nie"],
                 "options_en":["Every 2 hours for ~15 minutes","Every 6 hours","Never"],
                 "answer":0,"e_de":"Regelmaessige Pausen beugen Muedigkeit vor.","e_en":"Regular breaks prevent fatigue."},
                {"q_de":"Zeichen von Muedigkeit sind:",
                 "q_en":"Signs of fatigue include:",
                 "options_de":["Gaehnen, schwere Augen, Strecke verpasst","Extreme Wachheit","Schnelle Reaktionen"],
                 "options_en":["Yawning, heavy eyes, missed exits","Extreme alertness","Fast reactions"],
                 "answer":0,"e_de":"Bei Muedigkeit sofort anhalten und ruhen.","e_en":"If tired, stop and rest immediately."},
                {"q_de":"Wenn Sie muede sind, sollten Sie:",
                 "q_en":"If you feel drowsy you should:",
                 "options_de":["Anhalten und eine Pause machen","Nur das Fenster oeffnen","Beschleunigen"],
                 "options_en":["Pull over and take a break","Just open the window","Speed up"],
                 "answer":0,"e_de":"Frische Luft beendet Muedigkeit nicht - halten Sie an.","e_en":"Fresh air alone will not fix tiredness - stop."},
                {"q_de":"Was bedeutet 'Gefahrenwahrnehmung'?",
                 "q_en":"What does 'hazard perception' mean?",
                 "options_de":["Gefahren frueh erkennen und rechtzeitig reagieren","Nur stark bremsen","Die Strasse ignorieren"],
                 "options_en":["Spot hazards early and react in time","Only brake hard","Ignore the road"],
                 "answer":0,"e_de":"Gefahrenwahrnehmung hilft, Unfaelle zu vermeiden.","e_en":"Hazard perception helps avoid crashes."},
                {"q_de":"Welche Gefahren sollten Sie voraussehen?",
                 "q_en":"Which hazards should you anticipate?",
                 "options_de":["Kind auf der Strasse, parkendes Auto, nasse Stelle","Nur andere Autos","Nur schoenes Wetter"],
                 "options_en":["Child on road, parked car door, wet patch","Only other cars","Only good weather"],
                 "answer":0,"e_de":"Gefahren sind alles, was Sie bremsen oder ausweichen laesst.","e_en":"Hazards are anything that makes you slow or steer."},
                {"q_de":"Gute Fahrer schauen staendig:",
                 "q_en":"Good drivers constantly look at:",
                 "options_de":["Voraus, in den Spiegel, an Kreuzungen","Nur auf die Motorhaube","Nur aufs Radio"],
                 "options_en":["Ahead, mirrors, junctions","Only the bonnet","Only the radio"],
                 "answer":0,"e_de":"Vorausschauendes Schauen erkennt Gefahren frueh.","e_en":"Forward scanning spots hazards early."},
                {"q_de":"Wenn ein Ball auf die Strasse rollt, sollten Sie:",
                 "q_en":"If a ball rolls onto the road you should:",
                 "options_de":["Langsamer fahren und bereit zum Anhalten sein","Beschleunigen","Ignorieren"],
                 "options_en":["Slow down and be ready to stop","Speed up","Ignore it"],
                 "answer":0,"e_de":"Ein Kind koennte hinterherlaufen - bremsbereit sein.","e_en":"A child may run after the ball - be ready to stop."},
                {"q_de":"Bei Nasse verlaengert sich der Bremsweg etwa:",
                 "q_en":"In the wet, stopping distance roughly:",
                 "options_de":["Verdoppelt sich","Bleibt gleich","Halbiert sich"],
                 "options_en":["Doubles","Stays the same","Halves"],
                 "answer":0,"e_de":"Nasse Strassen verdoppeln den Bremsweg - Abstand erhoehen.","e_en":"Wet roads double stopping distance - increase your gap."},
                {"q_de":"Auf Landstrassen koennen auftauchen:",
                 "q_en":"On country roads you may encounter:",
                 "options_de":["Wildtiere (Rehwild) und Landwirtschaft","Nur Stadtbusse","Nur Schienen"],
                 "options_en":["Wild animals and farm traffic","Only city buses","Only tram tracks"],
                 "answer":0,"e_de":"Mit Wild rechnen, besonders bei Daemmerung - langsamer fahren.","e_en":"Expect wildlife, especially at dusk - slow down."},
                {"q_de":"Wenn Sie ein Tier anfahren, muessen Sie:",
                 "q_en":"If you hit an animal you must:",
                 "options_de":["Unfall melden (Polizei/Halter)","Weiterfahren","Nichts tun"],
                 "options_en":["Report it (police / owner)","Drive on","Do nothing"],
                 "answer":0,"e_de":"Ein Wildunfall ist meldepflichtig.","e_en":"A wildlife collision must be reported."},
                {"q_de":"Auf Landstrassen nachts sollten Sie achten auf:",
                 "q_en":"On country roads at night watch for:",
                 "options_de":["Tieraugen / Schatten auf der Fahrbahn","Nur andere Autos","Strassenlaternen"],
                 "options_en":["Animal eyes / shadows on the road","Only other cars","Street lights"],
                 "answer":0,"e_de":"Tiere sind nachts schwer zu sehen - langsamer fahren.","e_en":"Animals are hard to see at night - slow down."},
                {"q_de":"Weit voraus schauen hilft Ihnen:",
                 "q_en":"Looking well ahead helps you:",
                 "options_de":["Sanft bremsen statt Vollbremsung","Schneller fahren","Den Spiegel ignorieren"],
                 "options_en":["Brake gently instead of slamming","Drive faster","Ignore the mirror"],
                 "answer":0,"e_de":"Fruehes Erkennen ermoeglicht sanftes Bremsen.","e_en":"Early recognition allows smooth braking."},
                {"q_de":"An einem Strassenkamm (Kuppen) sollten Sie:",
                 "q_en":"At the crest of a hill you should:",
                 "options_de":["Langsamer fahren und rechts halten","Beschleunigen","Sofort ueberholen"],
                 "options_en":["Slow down and keep right","Accelerate","Overtake immediately"],
                 "answer":0,"e_de":"Hinter der Kuppe kann eine Gefahr lauern.","e_en":"A hazard may be hidden beyond the crest."},
                {"q_de":"Bei 100 km/h ist ein sicherer Abstand etwa:",
                 "q_en":"At 100 km/h a safe gap is about:",
                 "options_de":["3 Sekunden oder mehr","1 Sekunde","Eine halbe Sekunde"],
                 "options_en":["3 seconds or more","1 second","Half a second"],
                 "answer":0,"e_de":"Hoehere Geschwindigkeit braucht mehr Abstand.","e_en":"Higher speeds need longer gaps."},
                {"q_de":"Wenn der Vordermann bremsen uebt, reagieren Sie:",
                 "q_en":"If the driver ahead brake-checks you, respond by:",
                 "options_de":["Abstand halten, nicht aggressiv reagieren","Dicht auffahren","Scharf ueberholen"],
                 "options_en":["Keep distance, do not react aggressively","Tailgate","Overtake sharply"],
                 "answer":0,"e_de":"Bleiben Sie ruhig - Ihre Sicherheit zaehlt.","e_en":"Stay calm - your safety comes first."},
                {"q_de":"Tempomat auf einer ruhigen, ebenen Strecke ist:",
                 "q_en":"Cruise control on a calm, steady road is:",
                 "options_de":["In Ordnung bei klarem Verkehr","Immer verboten","Nur in der Stadt"],
                 "options_en":["Fine in clear, light traffic","Always illegal","Only in the city"],
                 "answer":0,"e_de":"Bei wechselndem Verkehr Tempomat ausschalten.","e_en":"Turn it off in changing traffic."},
                {"q_de":"Schon 'ein oder zwei Biere' koennen:",
                 "q_en":"Even 'one or two beers' can:",
                 "options_de":["Das Urteilsvermoegen trueben und ueber 0,5 fuehren","Das Fahren verbessern","Keine Wirkung haben"],
                 "options_en":["Impair judgement and take you over 0.05","Improve driving","Have no effect"],
                 "answer":0,"e_de":"Schon wenig Alkohol beeintraechtigt.","e_en":"Even small amounts of alcohol impair you."},
                {"q_de":"Wenn Sie trinken wollen, ist die sichere Wahl:",
                 "q_en":"If you plan to drink, the safe choice is:",
                 "options_de":["Fahrgemeinschaft, Taxi oder OEPNV nutzen","Trotzdem selbst fahren","Schneller heimfahren"],
                 "options_en":["Use a designated driver, taxi or public transport","Still drive yourself","Drive home faster"],
                 "answer":0,"e_de":"Nie mit Alkohol fahren - vorher einen Plan haben.","e_en":"Never drive after drinking - plan ahead."},
                {"q_de":"Was bedeutet 'defensives Fahren'?",
                 "q_en":"What does 'defensive driving' mean?",
                 "options_de":["Vorausschauend und ruecksichtsvoll fahren","Aggressiv draengeln","Nur schnell fahren"],
                 "options_en":["Anticipate and drive considerately","Aggressively push","Just drive fast"],
                 "answer":0,"e_de":"Defensives Fahren vermeidet Konflikte und Unfaelle.","e_en":"Defensive driving avoids conflict and crashes."},
                {"q_de":"Bei schlechtem Wetter (Regen/Schnee) sollten Sie:",
                 "q_en":"In bad weather (rain/snow) you should:",
                 "options_de":["Tempo anpassen und Abstand erhoehen","Wie gewohnt fahren","Beschleunigen"],
                 "options_en":["Reduce speed and increase distance","Drive as usual","Speed up"],
                 "answer":0,"e_de":"Witterung verlaengert Bremswege.","e_en":"Weather lengthens stopping distances."},
                {"q_de":"Bei Aquaplaning sollten Sie:",
                 "q_en":"In aquaplaning you should:",
                 "options_de":["Vom Gas gehen, nicht bremsen","Hart bremsen","Lenkrad ruckartig drehen"],
                 "options_en":["Ease off the accelerator, do not brake","Brake hard","Jerk the wheel"],
                 "answer":0,"e_de":"Bei Aquaplaning lenkt das Fahrzeug nicht - nur Gas wegnehmen.","e_en":"In aquaplaning the car will not steer - just ease off the throttle."},
                {"q_de":"Bei einer Panne auf der Autobahn:",
                 "q_en":"In a breakdown on the motorway:",
                 "options_de":["Warndreieck aufstellen, Weste anziehen, Notruf 112","Auf der Fahrbahn reparieren","Weiterfahren"],
                 "options_en":["Set warning triangle, wear vest, call 112","Repair on the lane","Keep driving"],
                 "answer":0,"e_de":"Sicherheit geht vor - Warnweste anziehen und Notruf waehlen.","e_en":"Safety first - wear the vest and call emergency services."},
                {"q_de":"Die europaweite Notrufnummer ist:",
                 "q_en":"The Europe-wide emergency number is:",
                 "options_de":["112","911","110 nur in Deutschland","100"],
                 "options_en":["112","911","110 Germany only","100"],
                 "answer":0,"e_de":"112 erreicht Rettungsdienst und Feuerwehr in ganz Europa.","e_en":"112 reaches ambulance and fire services across Europe."},
                {"q_de":"Eine Warnweste muss im Auto mitgefuehrt werden und:",
                 "q_en":"A warning vest must be carried and:",
                 "options_de":["Beim Verlassen des Fahrzeugs auf der Autobahn angezogen werden","Nur im Kofferraum bleiben","Nie getragen werden"],
                 "options_en":["Be worn when leaving the car on the motorway","Stay only in the boot","Never be worn"],
                 "answer":0,"e_de":"Die Weste erhoeht die Sichtbarkeit bei Panne.","e_en":"The vest makes you visible during a breakdown."}
            ]
        }
    ]
}
