#!/usr/bin/env python3
"""Ireland DTT (Driver Theory Test) practice data - public-domain-style.

The Irish DTT is a single national test run by the RSA (Road Safety
Authority) and is based on the Irish Rules of the Road. Ireland drives on
the LEFT, like the UK. Questions are grouped into the four practice modes
used on the site:
  - full    : all questions mixed (auto-built by generator)
  - signs   : Road & Traffic Signs
  - rules   : Rules of the Road & Safety
  - alcohol : Alcohol, Drugs & Hazard Perception
Every question carries an explanation (the 'why'). Used by _gen_ie.py.
"""
IE = {
    "name": "Ireland (DTT) Practice Test",
    "source": "Irish Rules of the Road / RSA DTT syllabus (public domain style)",
    "categories": [
        {
            "id": "signs",
            "title": "Road & Traffic Signs",
            "blurb": "Regulatory, warning and information signs used on Irish roads.",
            "questions": [
                {"q": "What shape and colour is a STOP sign in Ireland?",
                 "options": ["Red octagon with the word STOP", "Red triangle with GIVE WAY", "Blue rectangle"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "A STOP sign is a red octagon, shaped so it is recognised at night without reading it."},
                {"q": "A GIVE WAY sign in Ireland is shaped like:",
                 "options": ["A red inverted triangle with white GIVE WAY", "A red octagon", "A blue circle"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Ireland uses a red inverted triangle for give way; you must give way to traffic on the continuing road."},
                {"q": "A red circle with a number inside (e.g. 50) means:",
                 "options": ["Maximum speed limit of 50 km/h", "Minimum speed of 50 km/h", "An advisory speed only"],
                 "answer": 0, "ref": "Speed signs",
                 "explanation": "A red-ringed circle is a maximum speed limit - you must not exceed the number shown."},
                {"q": "A red circle with a horizontal white bar means:",
                 "options": ["No entry", "Give way", "Stop"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "The red circle with a white horizontal bar is the 'no entry' sign - you must not enter that road."},
                {"q": "Warning signs in Ireland are generally:",
                 "options": ["Triangular with a red border", "Red circles", "Blue squares"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "Warning signs are red-bordered triangles that alert you to hazards ahead."},
                {"q": "A red-bordered triangle showing a railway track warns of:",
                 "options": ["A railway level crossing ahead", "Road works", "A school"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "The railway crossing warning means tracks cross the road ahead - slow down and be ready to stop."},
                {"q": "A red-bordered triangle showing children warns of:",
                 "options": ["A school or place where children may be crossing", "A playground only", "A bus stop"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "Child warning signs mark schools and places where children are likely to cross."},
                {"q": "A pedestrian crossing warning sign means:",
                 "options": ["Pedestrians may be crossing - slow and give way", "No pedestrians", "Bicycles only"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "This warning tells you a pedestrian crossing is ahead, so slow and be ready to give way."},
                {"q": "Road work / construction signs are usually:",
                 "options": ["Orange diamonds or rectangles", "Blue squares", "White circles"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "Road work signs are orange to stand out; temporary speed limits with them are legally enforceable."},
                {"q": "Motorway signs in Ireland are:",
                 "options": ["Blue background with white text", "Green with yellow numbers", "Red with white text"],
                 "answer": 0, "ref": "Guide signs",
                 "explanation": "Irish motorway route signs have a blue background with white text and the 'M' route number."},
                {"q": "A yellow/orange diamond showing a slippery surface warns of:",
                 "options": ["A slippery road ahead", "The road narrowing", "A steep hill"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "The slippery road warning means reduce speed and avoid sudden braking or steering."},
                {"q": "A 'roundabout ahead' warning sign tells you to:",
                 "options": ["Slow down and prepare to give way", "Stop completely now", "Speed up"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "It warns a roundabout is coming; slow and be ready to give way to traffic on it."},
                {"q": "A red-and-white 'road closed' barrier sign means:",
                 "options": ["The road is closed - do not enter", "Detour is optional", "School zone only"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Road closed signs mean you must not proceed; follow the signed detour."},
                {"q": "A 'T-junction' warning sign means:",
                 "options": ["The road you are on ends - give way to the continuing road", "Merge left", "Roundabout ahead"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "At a T-junction the driver on the terminating road gives way to traffic on the continuing road."},
                {"q": "Dashed white lane lines mean:",
                 "options": ["You may change lanes when safe", "You must never cross them", "Cycle lane only"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "Dashed lines show you may change lanes when it is safe; solid lines restrict crossing."},
                {"q": "Double centre lines where the solid line is on YOUR side mean:",
                 "options": ["You must not cross or straddle them", "You may cross freely", "Parking allowed"],
                 "answer": 0, "ref": "Road markings",
                 "explanation": "If the solid line is on your side you must not cross or straddle the lines."},
                {"q": "A 'KEEP LEFT' sign tells you to:",
                 "options": ["Keep to the left of the line or island", "Overtake on the right", "The road is one-way right"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "Keep left signs tell you to stay to the left of a dividing line, island or obstruction."},
                {"q": "A sign showing a tram (LUAS) warns of:",
                 "options": ["Tram tracks / a tram crossing ahead (Dublin)", "A bus lane", "A railway only"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "In Dublin, LUAS tram warning signs mark where trams share the road - give way to trams."},
                {"q": "A 'wild animal' warning sign means:",
                 "options": ["Animals such as deer may be on the road", "Only pets", "A zoo nearby"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "In rural Ireland deer and livestock can appear on the road, especially at dusk."},
                {"q": "A 'NO OVERTAKING' sign is a red circle with:",
                 "options": ["Two cars, the one behind crossed out", "A speed number", "A bicycle"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "The no-overtaking sign bans passing the vehicle ahead until the restriction ends."},
                {"q": "A 'NO U-TURN' sign is a red circle with:",
                 "options": ["A U-turn symbol crossed out", "A blue square", "A yellow diamond"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "A red circle banning the U-turn means you must not turn back the way you came."},
                {"q": "A 'ONE WAY' sign tells you:",
                 "options": ["Traffic flows only in the arrow's direction", "It is a two-way road", "No entry ahead"],
                 "answer": 0, "ref": "Regulatory signs",
                 "explanation": "One-way signs mean you may only travel in the direction of the arrow."},
                {"q": "The 'national speed limit' sign is a white circle with:",
                 "options": ["A black diagonal stripe on a grey background", "A red ring and 80", "A blue square"],
                 "answer": 0, "ref": "Speed signs",
                 "explanation": "This sign ends a posted limit and returns you to the default national limits for that road type."},
                {"q": "A sign with a red ring and '30' means:",
                 "options": ["Maximum 30 km/h", "Minimum 30 km/h", "30 km/h at night only"],
                 "answer": 0, "ref": "Speed signs",
                 "explanation": "The red ring makes 30 a maximum speed limit for that stretch of road."},
                {"q": "A 'tram stop' or LUAS sign in Dublin means:",
                 "options": ["Watch for trams and passengers at stops", "Only buses stop here", "No stopping at all"],
                 "answer": 0, "ref": "Warning signs",
                 "explanation": "LUAS stops have platforms in the road; watch for trams arriving and people crossing."}
            ]
        },
        {
            "id": "rules",
            "title": "Rules of the Road & Safety",
            "blurb": "Speed limits, roundabouts, overtaking, seatbelts, phones and safe driving.",
            "questions": [
                {"q": "What is the default speed limit in a built-up area unless signs say otherwise?",
                 "options": ["50 km/h", "60 km/h", "40 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "In built-up areas the default limit is 50 km/h unless a sign shows a different limit."},
                {"q": "What is the default speed limit on a national road (e.g. N-road) unless signed?",
                 "options": ["100 km/h", "120 km/h", "80 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "On national roads the default limit is 100 km/h unless signs show otherwise."},
                {"q": "What is the maximum speed limit on an Irish motorway?",
                 "options": ["120 km/h", "130 km/h", "100 km/h"],
                 "answer": 0, "ref": "Speed limits",
                 "explanation": "The motorway limit in Ireland is 120 km/h unless a lower limit is signed."},
                {"q": "At a roundabout in Ireland you must:",
                 "options": ["Give way to traffic on the roundabout (from your right)", "Always have right of way", "Stop completely before entering"],
                 "answer": 0, "ref": "Roundabouts",
                 "explanation": "Traffic on the roundabout has priority; you give way to the right and signal your exit."},
                {"q": "At an unmarked junction you give way to:",
                 "options": ["Traffic coming from your right", "Traffic on your left", "The largest vehicle"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "With no signs or lines, give way to the vehicle on your right."},
                {"q": "When turning right at a junction you must give way to:",
                 "options": ["Oncoming traffic going straight or turning left", "Only oncoming traffic turning right", "No one"],
                 "answer": 0, "ref": "Give way",
                 "explanation": "Oncoming traffic going straight or turning left has priority over your right turn."},
                {"q": "Ireland drives on which side of the road?",
                 "options": ["The left", "The right", "Either side"],
                 "answer": 0, "ref": "General",
                 "explanation": "Ireland drives on the left, so you overtake on the right and give way accordingly."},
                {"q": "When overtaking you should:",
                 "options": ["Return to the left as soon as it is safe", "Stay in the right lane", "Speed up while overtaking"],
                 "answer": 0, "ref": "Overtaking",
                 "explanation": "After passing, move back to the left in good time and do not cut in front of the other vehicle."},
                {"q": "A fully licensed driver may use a phone while driving if:",
                 "options": ["It is secured in a cradle and used hands-free", "They hold it briefly", "Only at traffic lights"],
                 "answer": 0, "ref": "Mobile phones",
                 "explanation": "Even full licence holders may only use a phone fixed in a cradle and operated hands-free."},
                {"q": "Learner (L) and novice (N) drivers must:",
                 "options": ["Not use a phone at all, including hands-free", "May use it hands-free", "May hold it at lights"],
                 "answer": 0, "ref": "Mobile phones",
                 "explanation": "Learner and novice drivers are banned from any phone use while driving, including hands-free."},
                {"q": "Seatbelts must be worn by:",
                 "options": ["All occupants of the vehicle", "The driver only", "Front-seat passengers only"],
                 "answer": 0, "ref": "Restraints",
                 "explanation": "Every occupant must wear a fitted seatbelt; the driver is responsible for child passengers."},
                {"q": "Children must travel in:",
                 "options": ["An approved child restraint suited to their size", "The front seat at any age", "Any seat"],
                 "answer": 0, "ref": "Restraints",
                 "explanation": "Children must use an approved restraint suited to their age and size, usually in the rear."},
                {"q": "In good conditions you should keep a following gap of at least:",
                 "options": ["2 seconds", "1 second", "Touching distance"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Use the 2-second rule; it gives you time to react and stop safely."},
                {"q": "In wet weather you should:",
                 "options": ["At least double your following distance", "Keep the same gap", "Halve your gap"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Wet roads increase stopping distance, so increase your gap to 4 seconds or more."},
                {"q": "You may NOT stop or park within how many metres of a junction?",
                 "options": ["15 metres", "2 metres", "50 metres"],
                 "answer": 0, "ref": "Parking",
                 "explanation": "Do not stop or park within 15 metres of a junction, as it blocks the view of other drivers."},
                {"q": "Headlights must be on from:",
                 "options": ["30 minutes after sunset to 30 minutes before sunrise", "Only on motorways", "Never in cities"],
                 "answer": 0, "ref": "Lighting",
                 "explanation": "Use headlights between the half-hour after sunset and half-hour before sunrise, and in poor visibility."},
                {"q": "Fog lights should be used:",
                 "options": ["In fog or poor visibility", "Every night", "Only in rain"],
                 "answer": 0, "ref": "Lighting",
                 "explanation": "Fog lights are for seriously reduced visibility; using them otherwise can dazzle others."},
                {"q": "When you hear a Garda or ambulance siren you must:",
                 "options": ["Pull in to the left and let it pass", "Speed up to clear the way", "Ignore it"],
                 "answer": 0, "ref": "Emergency vehicles",
                 "explanation": "Pull over to the left and stop if needed so the emergency vehicle can pass."},
                {"q": "At a zebra or signal-controlled crossing you must:",
                 "options": ["Give way to pedestrians", "Only slow if they wave", "Keep going"],
                 "answer": 0, "ref": "Pedestrians",
                 "explanation": "Drivers must give way to pedestrians who are on or about to step onto a crossing."},
                {"q": "A school warden (lollipop person) showing a STOP sign means:",
                 "options": ["You must stop until they step back", "You may edge forward", "Only buses stop"],
                 "answer": 0, "ref": "Pedestrians",
                 "explanation": "You must obey a school warden's STOP sign and wait until children have crossed safely."},
                {"q": "A yellow box junction may only be entered when:",
                 "options": ["Your exit is clear", "You are in a hurry", "At any time"],
                 "answer": 0, "ref": "Junctions",
                 "explanation": "You may enter a yellow box only if your exit is clear, so you do not block the junction."},
                {"q": "At a railway level crossing with red lights or barriers you must:",
                 "options": ["Stop and only proceed when safe", "Cross quickly", "Reverse"],
                 "answer": 0, "ref": "Rail crossings",
                 "explanation": "Red lights or lowering barriers mean a train is coming - stop and wait until it is safe."},
                {"q": "When a tram (LUAS) is stopping at a platform you should:",
                 "options": ["Not overtake it between the tram and the left kerb", "Overtake on the right at speed", "Drive around it"],
                 "answer": 0, "ref": "Trams",
                 "explanation": "In Dublin you must not pass a stopping tram on the left where passengers are boarding or alighting."},
                {"q": "You must carry your driving licence:",
                 "options": ["Whenever you are driving", "Only on long trips", "Never"],
                 "answer": 0, "ref": "Documents",
                 "explanation": "You must have your licence with you when driving and show it if Gardai ask."},
                {"q": "A newly qualified driver must display:",
                 "options": ["An 'N' plate for two years", "Nothing", "An 'L' plate forever"],
                 "answer": 0, "ref": "Licensing",
                 "explanation": "After passing the test, drivers must display N plates for two years as novice drivers."}
            ]
        },
        {
            "id": "alcohol",
            "title": "Alcohol, Drugs & Hazard Perception",
            "blurb": "BAC limits, drug driving, fatigue, penalty points and spotting hazards.",
            "questions": [
                {"q": "The legal blood alcohol concentration (BAC) limit for a fully licensed driver is:",
                 "options": ["0.05", "0.00", "0.08"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Most full licence holders must stay at or below a BAC of 0.05."},
                {"q": "Learner (L) and novice (N) drivers must have a BAC of:",
                 "options": ["0.02", "0.05", "0.00"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Learner and novice drivers must stay at or below 0.02 BAC - a lower limit applies."},
                {"q": "Driving with a BAC over the legal limit is:",
                 "options": ["A serious criminal offence", "A minor issue", "Allowed if you feel fine"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Drink driving carries fines, penalty points, a driving ban and possible imprisonment."},
                {"q": "Driving under the influence of drugs is:",
                 "options": ["Illegal and can be tested at the roadside", "Allowed in small amounts", "Only illegal at night"],
                 "answer": 0, "ref": "Drug driving",
                 "explanation": "Drug driving is illegal; Gardai can conduct roadside drug tests."},
                {"q": "If a medicine you take causes drowsiness you should:",
                 "options": ["Not drive until its effect has worn off", "Drive only on quiet roads", "Drive at night"],
                 "answer": 0, "ref": "Drug driving",
                 "explanation": "Any drug that makes you drowsy makes driving unsafe; do not drive until it has cleared."},
                {"q": "To manage fatigue on a long drive you should take a break at least every:",
                 "options": ["2 hours", "6 hours", "Rarely"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Stop for a break at least every two hours to restore alertness."},
                {"q": "Signs that you are too tired to drive include:",
                 "options": ["Yawning, heavy eyes and missing exits", "Feeling extra alert", "Faster reactions"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Yawning, sore eyes and lapses in attention mean stop and rest immediately."},
                {"q": "If you feel drowsy while driving you should:",
                 "options": ["Pull over and rest", "Just open the window", "Accelerate to finish sooner"],
                 "answer": 0, "ref": "Fatigue",
                 "explanation": "Fresh air alone will not fix tiredness - stop in a safe place and rest."},
                {"q": "'Hazard perception' means:",
                 "options": ["Spotting dangers early and reacting in time", "Only braking hard", "Ignoring the road"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "It is the skill of identifying hazards ahead and acting early to avoid a crash."},
                {"q": "Which of these is a hazard you should anticipate?",
                 "options": ["A child near the road, a parked car door, a wet patch", "Only another car", "A clear sunny day"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Hazards include anything that could make you slow, stop or steer - not just other vehicles."},
                {"q": "Good drivers constantly scan:",
                 "options": ["Ahead, mirrors and junctions", "Only the bonnet", "The radio dial"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Scanning ahead and checking mirrors helps you see hazards before they become emergencies."},
                {"q": "If a ball rolls onto the road ahead you should:",
                 "options": ["Slow down and be ready to stop", "Speed up to pass", "Ignore it"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "A child may run after the ball, so slow early and prepare to stop."},
                {"q": "In the wet, your stopping distance at 50 km/h is roughly:",
                 "options": ["Double the dry distance", "About the same", "About half"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Wet roads can double stopping distance, so increase your gap and slow down."},
                {"q": "Country roads can have:",
                 "options": ["Sheep, cattle and wildlife", "Only city buses", "Tram tracks"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "Livestock and wildlife are common on rural Irish roads, especially at dawn and dusk."},
                {"q": "If you hit and injure a farm animal you must:",
                 "options": ["Report it to the owner or Gardai", "Drive on without stopping", "Do nothing"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "You must stop and report the incident to the owner or Gardai as soon as possible."},
                {"q": "On country roads at night you should watch for:",
                 "options": ["Animal eyes / shadows on the road", "Only other cars", "Streetlights"],
                 "answer": 0, "ref": "Rural hazards",
                 "explanation": "Animals are hard to see at night; reduce speed and watch the edges of the road."},
                {"q": "Looking well ahead helps you:",
                 "options": ["Brake gently in time instead of slamming", "Drive faster", "Skip the mirrors"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Early scanning lets you brake smoothly, which is safer and more comfortable."},
                {"q": "When approaching the crest of a hill you should:",
                 "options": ["Slow down and keep left", "Accelerate", "Overtake immediately"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "You cannot see over a crest, so slow and keep left in case a hazard is on the other side."},
                {"q": "At 100 km/h a safe following gap is about:",
                 "options": ["3 seconds or more", "1 second", "Half a second"],
                 "answer": 0, "ref": "Following distance",
                 "explanation": "Higher speeds need longer gaps; aim for at least 3 seconds and more in poor conditions."},
                {"q": "If the driver ahead brake-checks you, the safe response is to:",
                 "options": ["Keep a safe distance and not react aggressively", "Brake hard and tailgate", "Overtake sharply"],
                 "answer": 0, "ref": "Hazard perception",
                 "explanation": "Stay calm, keep your distance and avoid escalating - your safety comes first."},
                {"q": "Cruise control on a long, steady road is:",
                 "options": ["Fine when conditions are light and clear", "Always illegal", "Only for city use"],
                 "answer": 0, "ref": "Vehicle handling",
                 "explanation": "Cruise control is useful on steady roads but turn it off in heavy or changing traffic."},
                {"q": "Even 'a couple of drinks' can:",
                 "options": ["Impair judgement and push you over the limit", "Improve your driving", "Have no effect"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Small amounts of alcohol still affect judgement and can take you over 0.05."},
                {"q": "A learner driver must be accompanied by:",
                 "options": ["A qualified driver who holds a full licence", "Another learner", "No one"],
                 "answer": 0, "ref": "Licensing",
                 "explanation": "A learner must be supervised by a full licence holder and display L plates."},
                {"q": "How many penalty points can disqualify a full licence holder in 3 years?",
                 "options": ["12 points", "4 points", "20 points"],
                 "answer": 0, "ref": "Penalty points",
                 "explanation": "A full licence holder is disqualified at 12 penalty points in any 3-year period; learners/novices at 7."},
                {"q": "If you plan to drink, the safe choice is to:",
                 "options": ["Arrange a designated driver, taxi or rideshare", "Still drive home", "Drive faster to get home"],
                 "answer": 0, "ref": "Alcohol limits",
                 "explanation": "Plan ahead: never drive after drinking - use a sober driver or public transport."}
            ]
        }
    ]
}
