#!/usr/bin/env python3
"""UK DVSA Theory Test practice data — public-domain-style questions.
The UK theory test is a SINGLE national pool (England, Wales, Scotland share
the same DVSA question bank; Northern Ireland is separate but similar). There
is NO regional variation in the main GB test. Questions below are grouped by
the official DVSA theory test syllabus categories and each carries an
explanation (the 'why'). Used by _gen_uk.py to build /uk/.
"""
UK = {
    "name": "UK (DVSA Theory Test)",
    "source": "DVSA theory test syllabus (public domain style)",
    "questions": [
        # --- Alertness ---
        {"q": "What is the national speed limit for cars on a single carriageway in the UK?",
         "options": ["50 mph", "60 mph", "70 mph"], "answer": 1,
         "ref": "Speed limits",
         "explanation": "On a single carriageway the national speed limit for cars is 60 mph unless signs show otherwise."},
        {"q": "Before a long motorway journey you should:",
         "options": ["Check tyres, oil, water and fuel", "Only check fuel", "Nothing, the car is fine"],
         "answer": 0, "ref": "Vehicle checks",
         "explanation": "Before a long trip, check tyre pressures, oil, coolant and fuel levels to avoid breakdowns."},
        {"q": "You are feeling tired and drowsy while driving. What should you do?",
         "options": ["Stop in a safe place and rest", "Open the window and continue", "Drive faster to arrive sooner"],
         "answer": 0, "ref": "Alertness",
         "explanation": "Tiredness kills. Stop in a safe place, have a break or a nap rather than risk falling asleep at the wheel."},
        {"q": "What can cause you to lose concentration while driving?",
         "options": ["Using a mobile phone", "Both hands on the wheel", "Looking in your mirrors regularly"],
         "answer": 0, "ref": "Alertness",
         "explanation": "Using a handheld phone severely distracts you; it is also illegal and carries penalty points and a fine."},
        {"q": "You take medicine that makes you feel drowsy. You should:",
         "options": ["Not drive until it has worn off", "Drive only on quiet roads", "Drive faster to finish sooner"],
         "answer": 0, "ref": "Alertness / drugs",
         "explanation": "Any drug (including prescription medicine) that causes drowsiness makes driving unsafe and may be illegal."},
        {"q": "How can you spot if you are about to fall asleep at the wheel?",
         "options": ["Difficulty keeping your eyes open", "The radio sounding clearer", "Your speed decreasing"],
         "answer": 0, "ref": "Alertness",
         "explanation": "Heavy eyelids, yawning and nodding are warning signs. Stop and rest immediately."},
        {"q": "A driver uses a hands-free phone. Is this safe?",
         "options": ["Still distracting, avoid when possible", "Completely safe", "Only illegal at night"],
         "answer": 0, "ref": "Alertness",
         "explanation": "Hands-free is legal but still divides your attention; avoid calls in complex or busy traffic."},

        # --- Attitude ---
        {"q": "What does a red traffic light mean?",
         "options": ["Stop and wait behind the stop line", "Proceed if no one is coming", "Slow down and prepare to stop"],
         "answer": 0, "ref": "Traffic signs",
         "explanation": "A red light means stop. Wait behind the stop line until the light shows green."},
        {"q": "What does a green traffic light mean?",
         "options": ["Go if it is safe", "Go regardless", "Stop"],
         "answer": 0, "ref": "Traffic signs",
         "explanation": "Green means you may go, but only if it is safe and the junction is clear."},
        {"q": "You are approaching a roundabout. Who has priority?",
         "options": ["Traffic already on the roundabout", "Traffic approaching from the left", "Traffic approaching from the right"],
         "answer": 0, "ref": "Rules of the road",
         "explanation": "Traffic on the roundabout has priority; you give way to the right and signal your exit."},
        {"q": "When may you enter a box junction?",
         "options": ["When the exit is clear", "At any time if you are turning left", "Only during daylight"],
         "answer": 0, "ref": "Rules of the road",
         "explanation": "You may only enter a box junction if your exit is clear and you can cross without stopping in it."},
        {"q": "Amber traffic lights flashing near a school mean:",
         "options": ["Drive slowly and prepared to stop for children", "The road is closed", "No parking allowed"],
         "answer": 0, "ref": "Traffic signs",
         "explanation": "Flashing amber lights by a school mean slow down and be ready to stop for children."},
        {"q": "You want to turn right at a crossroads. Another car is coming from the left. Who goes first?",
         "options": ["The other driver (you give way from the right)", "You, because you are turning", "Whoever is fastest"],
         "answer": 0, "ref": "Right of way",
         "explanation": "At unmarked crossroads you give way to traffic from the right."},
        {"q": "What should your attitude be towards a learner driver?",
         "options": ["Patient and considerate", "Tailgate to make them hurry", "Overtake sharply"],
         "answer": 0, "ref": "Attitude",
         "explanation": "Be patient; learners need space and time. Aggressive driving increases risk for everyone."},
        {"q": "You are held up at a red light. When it turns green you should:",
         "options": ["Move off only when safe", "Rev the engine to hurry", "Immediately accelerate hard"],
         "answer": 0, "ref": "Attitude",
         "explanation": "Check it is safe before moving; another driver may still be clearing the junction."},
        {"q": "Why should you avoid using the horn late at night?",
         "options": ["It can disturb residents", "It is illegal anytime", "It damages the car"],
         "answer": 0, "ref": "Attitude",
         "explanation": "The horn should be used only to warn of danger; avoid it near homes between 11.30 pm and 7 am."},

        # --- Safety margins ---
        {"q": "You are driving on a wet road. Your stopping distance will be roughly how much longer than on a dry road?",
         "options": ["Twice as long", "The same", "Slightly shorter"], "answer": 0,
         "ref": "Safety margins",
         "explanation": "Wet roads can double your stopping distance, so increase your following gap."},
        {"q": "In good conditions the gap to the car in front should be at least:",
         "options": ["2 seconds", "0.5 seconds", "5 seconds only on motorways"], "answer": 0,
         "ref": "Safety margins",
         "explanation": "Use the two-second rule; double it in wet weather and increase further in ice or snow."},
        {"q": "What is the braking distance affected by?",
         "options": ["Speed, road and weather", "Only the colour of the car", "The radio volume"], "answer": 0,
         "ref": "Safety margins",
         "explanation": "Braking distance rises with speed and is lengthened by wet, icy or poor road surfaces."},
        {"q": "At 70 mph, compared with 30 mph, the stopping distance is roughly:",
         "options": ["About 7 times longer", "The same", "Half as long"], "answer": 0,
         "ref": "Safety margins",
         "explanation": "Stopping distance grows with the square of speed, so a small speed rise hugely increases distance."},
        {"q": "You are following a large vehicle. Why increase your distance?",
         "options": ["To see ahead and be seen", "To save fuel", "Because it is slower"], "answer": 0,
         "ref": "Safety margins",
         "explanation": "A bigger gap lets you see hazards earlier and gives the driver behind a clearer view of you."},

        # --- Hazard awareness ---
        {"q": "What is a 'hazard' in the theory test sense?",
         "options": ["Anything that could make you change speed or direction", "Only another car", "A speed camera"],
         "answer": 0, "ref": "Hazard awareness",
         "explanation": "A hazard is anything that might require you to slow down, stop or steer away."},
        {"q": "You see a ball bounce into the road ahead. You should:",
         "options": ["Slow down and be ready to stop", "Speed up to pass", "Ignore it"], "answer": 0,
         "ref": "Hazard awareness",
         "explanation": "A child may run after the ball; slow early and prepare to stop."},
        {"q": "At a blind bend you should:",
         "options": ["Slow down and keep left", "Accelerate to clear it", "Hoot continuously"], "answer": 0,
         "ref": "Hazard awareness",
         "explanation": "Reduce speed so you can stop if a hazard appears from the unseen side of the bend."},
        {"q": "Why should you check your mirrors before slowing?",
         "options": ["To warn following drivers", "It is not needed", "Only at night"], "answer": 0,
         "ref": "Hazard awareness",
         "explanation": "Knowing what is behind helps you brake in time and signal intentions to others."},
        {"q": "A pedestrian with a white stick and red band is:",
         "options": ["Deaf and blind", "Just blind", "A police officer"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "A white stick with a red band shows the person is both deaf and blind; take extra care."},

        # --- Vulnerable road users ---
        {"q": "You see a pedestrian waiting to cross at a zebra crossing. What should you do?",
         "options": ["Wave them to cross and stop", "Speed up to pass quickly", "Sound your horn"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "You must give way to pedestrians waiting at or on a zebra crossing."},
        {"q": "When overtaking a cyclist you should:",
         "options": ["Give plenty of room and not cut in", "Pass as close as possible", "Sound your horn first"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "Give cyclists plenty of space and do not cut back in too soon after passing."},
        {"q": "A horse rider is ahead on a narrow road. You should:",
         "options": ["Slow down and pass wide and slow", "Rev to warn them", "Overtake quickly"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "Horses can be startled; pass slowly, leave lots of room and be patient."},
        {"q": "Children near a school should make you:",
         "options": ["Drive slowly and watch for sudden moves", "Speed up to leave the area", "Ignore them"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "Children are unpredictable; slow down and be ready to stop near schools and parks."},
        {"q": "You are turning left into a side road and a cyclist is ahead. You should:",
         "options": ["Hold back until the cyclist is clear", "Cut in front of them", "Hoot them on"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "Cyclists may be ahead and hidden; let them clear before you turn across their path."},
        {"q": "An elderly pedestrian is crossing slowly. You should:",
         "options": ["Wait patiently", "Edge forward", "Sound horn"], "answer": 0,
         "ref": "Vulnerable road users",
         "explanation": "Older people may move slowly; wait and never pressure them with the horn."},
        {"q": "What does a toucan crossing allow?",
         "options": ["Pedestrians and cyclists together", "Only cars", "Only horses"], "answer": 0,
         "ref": "Crossings",
         "explanation": "A toucan crossing is shared by pedestrians and cyclists, who cross together."},

        # --- Weather conditions ---
        {"q": "How should you adjust your driving in fog?",
         "options": ["Use dipped headlights and reduce speed", "Use full beam", "Drive at normal speed"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "In fog use dipped headlights (or fog lights if visibility is very poor) and slow down."},
        {"q": "In heavy rain your tyres may 'aquaplane'. This means:",
         "options": ["They lose contact with the road", "They grip better", "They go flat"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "Aquaplaning is when a film of water lifts the tyres off the road; ease off the accelerator to regain grip."},
        {"q": "On ice your stopping distance can be up to:",
         "options": ["10 times the normal distance", "Half normal", "The same"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "Ice drastically reduces grip; leave a very large gap and drive gently."},
        {"q": "Strong winds are most dangerous for:",
         "options": ["High-sided vehicles and motorcyclists", "Only cyclists", "Cars at low speed"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "High-sided vehicles can be blown over and riders pushed; give them room in gusts."},
        {"q": "When driving in snow you should:",
         "options": ["Use the highest gear possible and accelerate gently", "Brake hard often", "Use low tyre pressure"],
         "answer": 0, "ref": "Weather conditions",
         "explanation": "A higher gear gives calmer power delivery and reduces wheel spin on snow."},
        {"q": "After a long dry spell, first rain makes roads specially slippery because:",
         "options": ["Oil and dust mix with water", "The road is colder", "Tyres harden"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "Built-up oil and dust become slippery when first wetted; drive with extra care."},
        {"q": "Dazzle from low sun can be reduced by:",
         "options": ["Using sun visor and slowing down", "Using full beam", "Closing one eye"], "answer": 0,
         "ref": "Weather conditions",
         "explanation": "A visor and slower speed help; keep your windscreen clean to cut glare."},

        # --- Road signs & markings ---
        {"q": "What does a circular sign with a red ring mean?",
         "options": ["A prohibition or limit", "A warning", "A direction"], "answer": 0,
         "ref": "Traffic signs",
         "explanation": "Circular signs with a red ring are orders — they prohibit or limit something."},
        {"q": "A red triangle warning sign means:",
         "options": ["Hazard ahead, slow down", "You must stop", "No entry"], "answer": 0,
         "ref": "Traffic signs",
         "explanation": "Triangular signs warn of hazards ahead such as bends, animals or junctions."},
        {"q": "What does a blue circular sign mean?",
         "options": ["A positive instruction", "A warning", "A speed limit"], "answer": 0,
         "ref": "Traffic signs",
         "explanation": "Blue circles give mandatory instructions, e.g. turn left or minimum speed."},
        {"q": "A white line along the edge of the road means:",
         "options": ["The edge of the carriageway", "A cycle lane", "A bus lane"], "answer": 0,
         "ref": "Road markings",
         "explanation": "A solid white edge line shows the boundary of the carriageway."},
        {"q": "Double white centre lines, one broken and one solid next to you, mean:",
         "options": ["You must not cross or straddle", "You may overtake freely", "It is a cycle path"], "answer": 0,
         "ref": "Road markings",
         "explanation": "If the solid line is on your side, you must not cross or straddle the line."},
        {"q": "A yellow box marking on the road means:",
         "options": ["Do not stop in it unless exit is clear", "Parking allowed", "Bus only"], "answer": 0,
         "ref": "Road markings",
         "explanation": "You may enter a yellow box only if your exit is clear to avoid blocking the junction."},
        {"q": "What shape are most warning signs?",
         "options": ["Triangular", "Circular", "Square"], "answer": 0,
         "ref": "Traffic signs",
         "explanation": "Warning signs are red-bordered triangles to alert you to hazards ahead."},
        {"q": "A 'STOP' sign is what shape and colour?",
         "options": ["Octagonal, red", "Circular, blue", "Rectangular, green"], "answer": 0,
         "ref": "Traffic signs",
         "explanation": "The unique octagonal red STOP sign means you must stop at the line."},

        # --- Documents & licensing ---
        {"q": "What is the legal alcohol limit for drivers in England, Wales and Northern Ireland?",
         "options": ["35 micrograms of alcohol per 100 ml of breath", "50 micrograms per 100 ml of breath", "20 micrograms per 100 ml of breath"],
         "answer": 0, "ref": "Alcohol",
         "explanation": "The breath limit is 35 micrograms of alcohol per 100 ml of breath in England, Wales and NI."},
        {"q": "In Scotland the breath alcohol limit is:",
         "options": ["22 micrograms per 100 ml", "35 micrograms per 100 ml", "50 micrograms per 100 ml"],
         "answer": 0, "ref": "Alcohol",
         "explanation": "Scotland has a lower limit of 22 micrograms per 100 ml of breath."},
        {"q": "You must always carry which document when driving?",
         "options": ["Your driving licence", "Your birth certificate", "A passport"], "answer": 0,
         "ref": "Documents",
         "explanation": "You must produce your driving licence and insurance if asked by police; keep them with you or accessible."},
        {"q": "What must you have to drive legally on public roads?",
         "options": ["A valid licence, insurance and road tax", "Just a licence", "Just insurance"], "answer": 0,
         "ref": "Documents",
         "explanation": "You need a valid driving licence, at least third-party insurance and current vehicle tax (or exemption)."},
        {"q": "A new driver in the UK can be banned if they get how many points in 2 years?",
         "options": ["6 or more", "2 or more", "12 or more only after 2 years"], "answer": 0,
         "ref": "Licensing",
         "explanation": "New drivers (within 2 years) risk revocation at 6 points; experienced drivers at 12."},
        {"q": "What is 'Continuous Insurance Enforcement'?",
         "options": ["Your vehicle must always be insured even if not driven", "Insurance only when driving", "Tax covers insurance"],
         "answer": 0, "ref": "Documents",
         "explanation": "Every registered vehicle must have insurance at all times unless officially off-road (SORN)."},

        # --- Accidents & incidents ---
        {"q": "What should you do at the scene of a crash where someone is injured?",
         "options": ["Call 999, warn others, give first aid if safe", "Drive away", "Move all cars immediately"], "answer": 0,
         "ref": "Incidents",
         "explanation": "Alert emergency services, make the scene safe and help the injured without putting yourself at risk."},
        {"q": "What is the purpose of an amber reflective jacket?",
         "options": ["To make you visible if you break down", "To look stylish", "It is required only at night"], "answer": 0,
         "ref": "Incidents",
         "explanation": "A high-visibility jacket helps others see you if you have to stop on the roadside."},
        {"q": "If you break down on a motorway you should:",
         "options": ["Use an emergency telephone and wait safe", "Stand in the lane to warn others", "Repair it in the lane"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "On a motorway, use the emergency telephone and stay well away from traffic if possible."},
        {"q": "A warning triangle should be placed how far from a broken-down car on a motorway?",
         "options": ["Not used on motorways", "50 metres behind", "10 metres behind"], "answer": 0,
         "ref": "Incidents",
         "explanation": "Never use a warning triangle on a motorway; use the emergency phone instead."},
        {"q": "After an accident you should give your details to:",
         "options": ["The other driver and police if needed", "Nobody", "Only your insurer later"], "answer": 0,
         "ref": "Incidents",
         "explanation": "Exchange name, address and insurer details with the other party; report to police if injured."},
        {"q": "If you spill fuel or oil on the road you should:",
         "options": ["Tell the police or highway authority", "Leave it", "Wash it with water"], "answer": 0,
         "ref": "Incidents",
         "explanation": "Spilt fuel is a hazard; inform the police or highway authority so it can be cleaned."},

        # --- Vehicle loading & handling ---
        {"q": "Before a long journey you should check:",
         "options": ["Tyres, lights, fluid and load", "Only the radio", "Nothing"], "answer": 0,
         "ref": "Vehicle checks",
         "explanation": "Basic checks reduce breakdown risk and keep the car legal and safe."},
        {"q": "A heavy load on the roof will mainly affect:",
         "options": ["The vehicle's stability and fuel use", "Only the tyres' colour", "Nothing"], "answer": 0,
         "ref": "Vehicle loading",
         "explanation": "Roof loads raise the centre of gravity and worsen handling, especially in corners."},
        {"q": "If your car is heavily loaded you should:",
         "options": ["Increase tyre pressures and allow longer braking", "Lower tyre pressures", "Drive faster"], "answer": 0,
         "ref": "Vehicle loading",
         "explanation": "Heavier loads need more stopping distance and may require higher tyre pressures per the manual."},
        {"q": "Towing a trailer affects your:",
         "options": ["Braking distance and stability", "Only fuel cost", "Nothing"], "answer": 0,
         "ref": "Vehicle loading",
         "explanation": "Trailers add weight and length, increasing braking distance and the risk of snaking."},
        {"q": "What is the correct tyre tread depth minimum in the UK?",
         "options": ["1.6 mm across the central 3/4", "1 mm anywhere", "3 mm all over"], "answer": 0,
         "ref": "Vehicle checks",
         "explanation": "Law requires at least 1.6 mm of tread over the central three-quarters of the tyre."},

        # --- Motorway rules ---
        {"q": "What is the maximum speed limit on a motorway for cars?",
         "options": ["70 mph", "60 mph", "80 mph"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "The national motorway limit for cars is 70 mph unless signs show otherwise."},
        {"q": "Which lane should you normally use on a motorway?",
         "options": ["The left-hand lane", "The middle lane", "The right-hand lane"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "Keep to the left lane and only use others for overtaking, then move back."},
        {"q": "You must NOT stop on a motorway except:",
         "options": ["In an emergency or a service area", "For a phone call", "To read a map"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "Stopping is only allowed in an emergency, in a lay-by, or at a service area."},
        {"q": "A red cross sign above a motorway lane means:",
         "options": ["Do not enter that lane", "Speed up", "It is a bus lane"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "A red cross shows the lane is closed; move to another lane in good time."},
        {"q": "Hard shoulder on a smart motorway may be used when:",
         "options": ["Only if a sign says it is open", "Whenever you like", "Only at night"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "On smart motorways the hard shoulder is only a running lane when signs permit it."},
        {"q": "When joining a motorway you should:",
         "options": ["Match the speed and merge safely", "Stop at the end of the slip road", "Force your way in"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "Build up speed on the slip road and merge with a safe gap in traffic."},

        # --- Attitude / eco / misc ---
        {"q": "Eco-safe driving means:",
         "options": ["Driving smoothly to save fuel and cut emissions", "Driving fast", "Idling often"], "answer": 0,
         "ref": "Eco-safe",
         "explanation": "Smooth acceleration, anticipation and correct tyre pressures save fuel and the environment."},
        {"q": "You are parked on the road. Before opening your door you should:",
         "options": ["Check for cyclists and pedestrians", "Open it quickly", "Only look in the mirror once"], "answer": 0,
         "ref": "Safety",
         "explanation": "Use the 'Dutch reach' and look before opening to avoid hitting a cyclist."},
        {"q": "Using cruise control in heavy traffic is:",
         "options": ["Not advised, you need full control", "Recommended", "Required by law"], "answer": 0,
         "ref": "Vehicle handling",
         "explanation": "Cruise control is for steady, light traffic; in busy roads you need instant control."},
        {"q": "You see roadworks ahead with a 40 mph sign. You should:",
         "options": ["Obey it and slow down", "Keep to 70 mph", "Ignore it"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "Temporary limits at roadworks are legally enforceable; workers and plant may be close."},
        {"q": "A speed limit sign with a red ring and 30 inside means:",
         "options": ["Maximum 30 mph, no faster", "Minimum 30 mph", "30 mph only at night"], "answer": 0,
         "ref": "Speed limits",
         "explanation": "A circular 30 sign is a maximum speed limit for that road."},
        {"q": "You are on a dual carriageway. The left lane ends. You should:",
         "options": ["Merge in good time", "Speed up to block", "Stop"], "answer": 0,
         "ref": "Roads",
         "explanation": "Move over early and safely when your lane is closing to avoid sudden merges."},
        {"q": "At night you should dip your headlights when:",
         "options": ["Approaching or following another vehicle", "Only on motorways", "Never"], "answer": 0,
         "ref": "Lighting",
         "explanation": "Dip beams prevent dazzling others; use full beam only when no one is ahead."},
        {"q": "You want to reverse into a side road. You should:",
         "options": ["Reverse in, it is safer than reversing out", "Always reverse out", "Never reverse"], "answer": 0,
         "ref": "Manoueuvres",
         "explanation": "Reversing into a side road means you drive out forwards with a clear view later."},
        {"q": "What is the purpose of a catalytic converter?",
         "options": ["Reduce harmful exhaust emissions", "Increase speed", "Cool the engine"], "answer": 0,
         "ref": "Environment",
         "explanation": "It cuts toxic gases; using leaded fuel or misfuelling can damage it."},
        {"q": "If your vehicle catches fire you should:",
         "options": ["Stop, get out and call 999", "Open the bonnet to check", "Keep driving to a garage"], "answer": 0,
         "ref": "Incidents",
         "explanation": "Get everyone clear and call the fire service; do not open the bonnet as air feeds the fire."},
        {"q": "You are driving a bus lane marked 'Buses only 7-9.30am'. At 10am you may:",
         "options": ["Use it", "Never use it", "Use it only if empty"], "answer": 0,
         "ref": "Road markings",
         "explanation": "Outside the stated times the restriction does not apply, so other traffic may use it."},
        {"q": "A driver behind is tailgating. You should:",
         "options": ["Increase your following gap to the car ahead", "Brake sharply", "Speed up"], "answer": 0,
         "ref": "Attitude",
         "explanation": "Leave more space ahead so you can brake gently and avoid being hit if you must stop."},
        {"q": "You miss your motorway exit. You should:",
         "options": ["Continue to the next exit", "Reverse on the hard shoulder", "Stop and turn"], "answer": 0,
         "ref": "Motorway rules",
         "explanation": "Never reverse or U-turn on a motorway; go to the next junction and re-route."},
        {"q": "What does a flashing green man at a pelican crossing mean?",
         "options": ["You may cross but it is about to change", "Stop immediately", "It is broken"], "answer": 0,
         "ref": "Crossings",
         "explanation": "A flashing green man tells pedestrians crossing is ending; do not start to cross."},
        {"q": "You should use your indicators to:",
         "options": ["Show your intended move in good time", "Only when someone is behind", "Never on roundabouts"], "answer": 0,
         "ref": "Signals",
         "explanation": "Signal early and clearly so others can plan; cancel afterwards to avoid confusion."}
    ]
}
